import * as T from '../vendor/three.module.js';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {GLTFLoader} from '../vendor/GLTFLoader.js';
import {RoomEnvironment} from '../vendor/RoomEnvironment.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const MODEL='double-strike-reference-1.0',KEY='progames-creator-draft-v1';
const COLORS={blue:{name:'Blue',hex:'#0069d8'},black:{name:'Black',hex:'#17191c'},white:{name:'White',hex:'#efeeeb'},red:{name:'Red',hex:'#c92330'},orange:{name:'Orange',hex:'#f66b12'},yellow:{name:'Yellow',hex:'#f2cb21'}};
const EQUIPMENT={card_reader:['Card reader','CARD_READER'],ticket_dispenser:['Ticket dispenser','TICKET_DISPENSER'],banknote_acceptor:['Banknote acceptor','BANKNOTE_ACCEPTOR'],coin_acceptor:['Additional coin slot','COIN_ACCEPTOR'],capsule_dispenser:['Capsule dispenser','CAPSULE_DISPENSER']};
const SURFACES={front:'CUSTOM_FRONT',left:'CUSTOM_LEFT',right:'CUSTOM_RIGHT'};
const defaults=()=>({color:'blue',equipment:[],factoryArtwork:true,leds:true,branding:{front:null,left:null,right:null}});
let state=defaults(),surface='front',id='',revision=0,ready=false,renderer,scene,camera,controls,model,host,observer,frame=0,autosave=0,noticeTimer=0,disposed=false,artBusy=0;
const assetTextures=new Set();const images={},brandTextures={},canvases={},uiAbort=new AbortController(),stats={frames:0,drawCalls:0,triangles:0};
let environmentTarget,screenOwnedTexture=null,contextLost=false;
function on(el,event,fn,options={}){el.addEventListener(event,fn,{...options,signal:uiAbort.signal});}
function say(message){$('#notice').textContent=message;$('#notice').classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('visible'),4500);}
function invalidate(){if(frame||disposed||contextLost||document.hidden)return;frame=requestAnimationFrame(()=>{frame=0;renderer.render(scene,camera);stats.frames++;stats.drawCalls=renderer.info.render.calls;stats.triangles=renderer.info.render.triangles;});}
function resize(){if(!renderer)return;const {width,height}=host.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();invalidate();}
function setView(view='default'){const target=new T.Vector3(0,1.1,0);const distance=camera.aspect<.7?4.55:4.25;let p=view==='front'?[0,1.35,distance]:view==='back'?[0,1.45,-distance]:view==='side'?[distance,1.45,0]:[distance*.67,1.83,distance*.79];camera.position.set(...p);controls.target.copy(target);controls.update();invalidate();}
function zoom(factor){camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);const d=camera.position.distanceTo(controls.target);if(d<2.2||d>6.5)camera.position.sub(controls.target).setLength(Math.max(2.2,Math.min(6.5,d))).add(controls.target);controls.update();invalidate();}
function cleanName(s){return String(s||'graphic').replace(/[\u0000-\u001f]/g,'').slice(0,100);}
async function digest(value){const data=new TextEncoder().encode(JSON.stringify({model:MODEL,...value}));if(!crypto.subtle)throw new Error('Use HTTPS or localhost to save configurations.');const h=await crypto.subtle.digest('SHA-256',data);return 'PGC-DS-'+[...new Uint8Array(h)].slice(0,10).map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();}
function snapshot(){return{schema:'progames-creator',version:1,model:MODEL,configurationId:id,savedAt:new Date().toISOString(),design:structuredClone(state)};}
function requestPayload(){return{configurationId:id,product:'Double Strike',modelVersion:MODEL,color:COLORS[state.color].name,equipment:state.equipment.map(k=>EQUIPMENT[k][0]),branding:Object.fromEntries(Object.entries(state.branding).map(([k,v])=>[k,v?{fileName:v.fileName,x:v.x,y:v.y,scale:v.scale,rotation:v.rotation}:null])),factoryArtwork:state.factoryArtwork,leds:state.leds,configuration:snapshot(),previewPng:null};}
function refreshSummary(){const eq=state.equipment.map(k=>EQUIPMENT[k][0]);const art=Object.keys(state.branding).filter(k=>state.branding[k]);$('#colourLabel').textContent=$('#summaryColour').textContent=COLORS[state.color].name;$('#equipmentCount').textContent=eq.length+' selected';$('#summaryEquipment').textContent=eq.join(', ')||'Standard';$('#brandingCount').textContent=art.length?art.length+' custom':state.factoryArtwork?'Factory':'Clean';$('#summaryBranding').textContent=art.length?'Custom: '+art.join(', '):state.factoryArtwork?'Factory':'No factory artwork';$('#configId').textContent=id||'Generating…';$$('#colours button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.color===state.color));$$('#equipment input').forEach(c=>c.checked=state.equipment.includes(c.value));$('#factoryGraphics').checked=state.factoryArtwork;$('#ledLights').checked=state.leds;}
async function changed({save=true}={}){const token=++revision;refreshSummary();$('#saveState').textContent='Updating design…';try{const result=await digest(state);if(token!==revision||disposed)return;id=result;refreshSummary();if(save){clearTimeout(autosave);autosave=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify(snapshot()));$('#saveState').textContent='Saved on this device';}catch{$('#saveState').textContent='Use Save design JSON';}},350);}else $('#saveState').textContent='Design ready';}catch(e){$('#saveState').textContent='Secure connection required';say(e.message);}}
function applyDesign(){renderer.shadowMap.needsUpdate=true;model.traverse(o=>{if(o.isMesh){const m=o.material;if(m?.name==='PAINT_BLUE')m.color.set(COLORS[state.color].hex);}});for(const [key,[,node]]of Object.entries(EQUIPMENT))model.getObjectByName(node).visible=state.equipment.includes(key);model.getObjectByName('FACTORY_GRAPHICS').visible=state.factoryArtwork;model.getObjectByName('LED_LIGHTS').visible=state.leds;for(const side of Object.keys(SURFACES))drawBrand(side);refreshArtControls();invalidate();}
function drawBrand(side){const node=model.getObjectByName(SURFACES[side]),art=state.branding[side];node.visible=!!art;if(!art)return;node.material.opacity=1;let canvas=canvases[side];if(!canvas){canvas=canvases[side]=document.createElement('canvas');canvas.width=side==='front'?512:256;canvas.height=1024;const tx=brandTextures[side]=new T.CanvasTexture(canvas);tx.colorSpace=T.SRGBColorSpace;tx.flipY=true;tx.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());node.material.map=tx;node.material.needsUpdate=true;}const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const im=images[side];if(im){const size=Math.min(canvas.width/im.width,canvas.height/im.height)*art.scale;ctx.save();ctx.translate(canvas.width*(.5+art.x/2),canvas.height*(.5+art.y/2));ctx.rotate(art.rotation*Math.PI/180);ctx.drawImage(im,-im.width*size/2,-im.height*size/2,im.width*size,im.height*size);ctx.restore();}brandTextures[side].needsUpdate=true;}
function refreshArtControls(){const art=state.branding[surface];$('#artFileName').textContent=art?art.fileName:'No custom graphic on this surface.';for(const [key,selector,factor]of [['x','artX',100],['y','artY',100],['scale','artScale',100],['rotation','artRotation',1]])$('#'+selector).value=art?Math.round(art[key]*factor):key==='scale'?65:0;$('#xValue').textContent=$('#artX').value+'%';$('#yValue').textContent=$('#artY').value+'%';$('#scaleValue').textContent=$('#artScale').value+'%';$('#rotationValue').textContent=$('#artRotation').value+'°';$$('#artControls input,#artControls button').forEach(x=>x.disabled=!art);$$('[data-surface]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.surface===surface));}
function decode(data){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>im.naturalWidth*im.naturalHeight>32000000?reject(new Error('Image resolution is too large. Use an image below 32 megapixels.')):resolve(im);im.onerror=()=>reject(new Error('This image could not be decoded. Please use PNG or JPG.'));im.src=data;});}
function fileData(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>reject(new Error('File could not be read.'));fr.readAsDataURL(file);});}
function safeSvg(text){const doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw new Error('Invalid SVG.');const allowed=new Set(['svg','g','path','rect','circle','ellipse','polygon','polyline','line','text','tspan','defs','linearGradient','radialGradient','stop','clipPath','mask','title','desc']);for(const el of [doc.documentElement,...doc.documentElement.querySelectorAll('*')]){if(!allowed.has(el.localName))throw new Error('SVG contains unsupported content. Export it as PNG.');for(const a of [...el.attributes]){if(a.name==='xmlns'&&a.value==='http://www.w3.org/2000/svg')continue;if(/^on/i.test(a.name)||/href/i.test(a.name)||/@import|javascript:|data:|https?:|\/\//i.test(a.value)||(/url\s*\(/i.test(a.value)&&!/^[^;]*url\(#[\w-]+\)[^;]*$/.test(a.value)))throw new Error('SVG must be self-contained, without scripts or external resources.');}}if(!doc.documentElement.getAttribute('width'))doc.documentElement.setAttribute('width','1024');if(!doc.documentElement.getAttribute('height'))doc.documentElement.setAttribute('height','1024');return new XMLSerializer().serializeToString(doc);}
async function rasterize(file){if(file.size>8*1024*1024)throw new Error('Maximum graphic size is 8 MB.');let data;if(file.type==='image/svg+xml'||/\.svg$/i.test(file.name)){const svg=safeSvg(await file.text());const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const im=await decode(url);data=toPng(im);}finally{URL.revokeObjectURL(url);}}else{if(!['image/png','image/jpeg'].includes(file.type))throw new Error('Use PNG, JPG or a self-contained SVG.');const im=await decode(await fileData(file));data=toPng(im);}return{data,image:await decode(data)};}
function toPng(im){const canvas=document.createElement('canvas'),s=Math.min(1,1024/Math.max(im.width,im.height));canvas.width=Math.max(1,Math.round(im.width*s));canvas.height=Math.max(1,Math.round(im.height*s));canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/png');}
async function upload(file){if(!file)return;const target=surface,token=++artBusy;try{say('Preparing graphic…');const {data,image}=await rasterize(file);if(token!==artBusy)return;images[target]=image;state.branding[target]={fileName:cleanName(file.name),data,x:0,y:0,scale:.65,rotation:0};drawBrand(target);refreshArtControls();invalidate();await changed();say('Graphic added to '+target+'.');}catch(e){say(e.message);}finally{$('#artUpload').value='';}}
function finite(value,min,max){return typeof value==='number'&&Number.isFinite(value)&&value>=min&&value<=max;}
async function validateConfig(input){if(input?.schema!=='progames-creator'||input.version!==1||input.model!==MODEL)throw new Error('This file belongs to another model or configuration format.');const d=input.design;if(!d||typeof d.color!=='string'||!Object.hasOwn(COLORS,d.color)||!Array.isArray(d.equipment)||d.equipment.length>5||d.equipment.some(k=>typeof k!=='string'||!Object.hasOwn(EQUIPMENT,k))||typeof d.factoryArtwork!=='boolean'||typeof d.leds!=='boolean'||!d.branding)throw new Error('Invalid configuration.');const next={color:d.color,equipment:[...new Set(d.equipment)].sort(),factoryArtwork:d.factoryArtwork,leds:d.leds,branding:{front:null,left:null,right:null}},decoded={};for(const side of Object.keys(SURFACES)){const art=d.branding[side];if(art==null)continue;if(typeof art.data!=='string'||art.data.length>6*1024*1024||!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(art.data)||!finite(art.x,-1,1)||!finite(art.y,-1,1)||!finite(art.scale,.1,2)||!finite(art.rotation,-180,180))throw new Error('Invalid branding data.');const im=await decode(art.data);if(im.width>1024||im.height>1024)throw new Error('Saved graphics must be at most 1024 pixels.');decoded[side]=im;next.branding[side]={fileName:cleanName(art.fileName),data:art.data,x:art.x,y:art.y,scale:art.scale,rotation:art.rotation};}return{next,decoded};}
async function importDesign(input){const {next,decoded}=await validateConfig(input);artBusy++;state=next;for(const side of Object.keys(SURFACES))images[side]=decoded[side]||null;applyDesign();await changed();say('Design restored.');}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function saveJSON(){await changed();download(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),id+'.json');say('Design JSON is ready. Keep it with your preview.');}
async function pngBlob(){renderer.render(scene,camera);const c=document.createElement('canvas');const target=renderer.domElement;c.width=target.width;c.height=target.height;const ctx=c.getContext('2d');ctx.drawImage(target,0,0);const font=Math.max(12,c.width/65);ctx.fillStyle='#202428';ctx.font='700 '+font+'px Arial';ctx.fillText('PRO GAMES CREATOR / DOUBLE STRIKE',font*1.4,c.height-font*3.0);ctx.font=font*.85+'px Arial';ctx.fillStyle='#72777d';ctx.fillText(id,font*1.4,c.height-font*1.55);return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Preview export failed.')),'image/png'));}
async function savePNG(){try{await changed();download(await pngBlob(),id+'.png');say('Preview downloaded.');}catch(e){say(e.message);}}
async function requestDesign(){await changed();const p=requestPayload();const art=Object.entries(p.branding).filter(([,v])=>v).map(([k,v])=>k+': '+v.fileName);const text=['Model: '+p.product,'Colour: '+p.color,'Equipment: '+(p.equipment.join(', ')||'Standard'),'Branding: '+(art.join('; ')||'None'),'Factory artwork: '+(p.factoryArtwork?'Yes':'No'),'LEDs: '+(p.leds?'On':'Off'),'Configuration ID: '+p.configurationId].join('\n');$('#requestSummary').textContent=text;$('#requestEmail').href='mailto:office@progames.pl?'+new URLSearchParams({subject:'PRO GAMES CREATOR enquiry — '+p.configurationId,body:'Hello PRO GAMES,\n\nPlease prepare a quote for this configuration:\n\n'+text+'\n\nDesign JSON and PNG preview: please attach manually.\nOptional mounting positions and final dimensions require confirmation.\n\nName:\nCompany:\nPhone:\n'}).toString();document.dispatchEvent(new CustomEvent('pgcreator:request',{detail:p}));$('#requestDialog').showModal();}
function fullPreview(){const full=$('#viewer').classList.toggle('full');document.body.classList.toggle('preview-open',full);$('#fullPreview').textContent=full?'Close preview ×':'Full preview ⛶';$('#fullPreview').setAttribute('aria-pressed',full);$('#panel').inert=full;$('.creator-header').inert=full;$('.creator-footer').inert=full;resize();}
function touchMode(){const active=host.classList.toggle('touch-active');controls.enableRotate=active||!matchMedia('(pointer:coarse)').matches;controls.enableZoom=active;$('#touchMode').textContent=active?'Allow page scrolling':'Enable touch rotation';$('#touchMode').setAttribute('aria-pressed',active);$('#viewerHint').textContent=active?'Drag to rotate · Pinch to zoom · Tap “Allow page scrolling” to finish':'Drag to rotate · Use + / − to zoom';}
function wire(){
 $('#colours').innerHTML=Object.entries(COLORS).map(([k,v])=>`<button type="button" data-color="${k}" style="--swatch:${v.hex}" title="${v.name}" aria-label="${v.name}" aria-pressed="${k==='blue'}"></button>`).join('');
 $('#equipment').innerHTML=Object.entries(EQUIPMENT).map(([k,v])=>`<label class="equipment-row"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><rect x="5" y="3" width="14" height="18" rx="3"/><path d="M8 7h8M8 11h8M9 17h6"/></svg><span>${v[0]}</span><input type="checkbox" value="${k}"></label>`).join('');
 for(const b of $$('#colours button'))on(b,'click',()=>{state.color=b.dataset.color;applyDesign();changed();});
 for(const c of $$('#equipment input'))on(c,'change',()=>{state.equipment=$$('#equipment input:checked').map(c=>c.value).sort();applyDesign();changed();});
 for(const b of $$('[data-surface]'))on(b,'click',()=>{surface=b.dataset.surface;refreshArtControls();setView(surface==='front'?'front':'side');if(surface==='left'){camera.position.x=-Math.abs(camera.position.x);controls.update();invalidate();}});
 on($('#artUpload'),'change',e=>upload(e.target.files[0]));
 for(const [selector,key,factor]of [['artX','x',100],['artY','y',100],['artScale','scale',100],['artRotation','rotation',1]])on($('#'+selector),'input',e=>{if(!state.branding[surface])return;state.branding[surface][key]=Number(e.target.value)/factor;drawBrand(surface);refreshArtControls();invalidate();changed();});
 on($('#resetArt'),'click',()=>{const a=state.branding[surface];if(a)Object.assign(a,{x:0,y:0,scale:.65,rotation:0});drawBrand(surface);refreshArtControls();invalidate();changed();});
 on($('#removeArt'),'click',()=>{artBusy++;state.branding[surface]=null;images[surface]=null;drawBrand(surface);refreshArtControls();invalidate();changed();});
 on($('#factoryGraphics'),'change',e=>{state.factoryArtwork=e.target.checked;applyDesign();changed();});on($('#ledLights'),'change',e=>{state.leds=e.target.checked;applyDesign();changed();});
 on($('#zoomIn'),'click',()=>zoom(.85));on($('#zoomOut'),'click',()=>zoom(1.18));on($('#resetCamera'),'click',()=>setView());$$('[data-view]').forEach(b=>on(b,'click',()=>setView(b.dataset.view)));on($('#fullPreview'),'click',fullPreview);on($('#touchMode'),'click',touchMode);
 on(document,'keydown',e=>{if(e.key==='Escape'&&$('#viewer').classList.contains('full'))fullPreview();if(e.key==='Tab'&&$('#viewer').classList.contains('full')){const controls=$$('#viewer button:not(:disabled),#canvasHost').filter(x=>x.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 on($('#saveJSON'),'click',saveJSON);on($('#downloadPNG'),'click',savePNG);on($('#requestJSON'),'click',saveJSON);on($('#requestPNG'),'click',savePNG);on($('#request'),'click',requestDesign);
 on($('#loadJSON'),'change',async e=>{const f=e.target.files[0];try{if(!f)return;if(f.size>16*1024*1024)throw new Error('Configuration file is too large.');await importDesign(JSON.parse(await f.text()));}catch(error){say(error.message==='Unexpected end of JSON input'?'Invalid JSON file.':error.message);}finally{e.target.value='';}});
 on($('#restoreLocal'),'click',async()=>{try{const saved=localStorage.getItem(KEY);if(!saved)throw new Error('No saved draft on this device.');await importDesign(JSON.parse(saved));}catch(e){say(e.message);}});
 on($('#resetDesign'),'click',()=>$('#resetDialog').showModal());on($('#resetDialog'),'close',()=>{if($('#resetDialog').returnValue!=='reset')return;artBusy++;state=defaults();Object.keys(images).forEach(k=>images[k]=null);applyDesign();setView();changed();say('Default design restored.');});
 on(document,'visibilitychange',()=>{if(!document.hidden)invalidate();});on(window,'pagehide',e=>{if(!e.persisted)dispose();});on(window,'pageshow',()=>invalidate());
}
async function loadModel(){const gltf=await new GLTFLoader().loadAsync(new URL('./assets/double-strike.glb',document.baseURI).href);return gltf.scene.getObjectByName('DOUBLE_STRIKE')||gltf.scene;}
function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(frame);clearTimeout(autosave);clearTimeout(noticeTimer);uiAbort.abort();observer?.disconnect();controls?.dispose();const geos=new Set(),mats=new Set(),textures=new Set();scene?.traverse(o=>{if(o.geometry)geos.add(o.geometry);for(const mat of [o.material].flat().filter(Boolean)){mats.add(mat);for(const v of Object.values(mat))if(v?.isTexture)textures.add(v);}});assetTextures.forEach(t=>textures.add(t));textures.forEach(t=>t.dispose());mats.forEach(m=>m.dispose());geos.forEach(g=>g.dispose());environmentTarget?.dispose();renderer?.dispose();}
export async function startCreator(){
 if(ready)return;host=$('#canvasHost');const start=performance.now();try{
 renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:false,powerPreference:'default'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<761?1.5:2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;host.append(renderer.domElement);
 scene=new T.Scene();scene.background=new T.Color(0xf6f6f3);camera=new T.PerspectiveCamera(35,1,.05,30);controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=false;controls.enableZoom=false;controls.enableRotate=!matchMedia('(pointer:coarse)').matches;controls.minDistance=2.2;controls.maxDistance=6.5;controls.minPolarAngle=.35;controls.maxPolarAngle=Math.PI*.52;controls.addEventListener('change',invalidate);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();environmentTarget=pmrem.fromScene(room,.06);scene.environment=environmentTarget.texture;scene.environmentIntensity=.65;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xffffff,0xc6c9d0,.75));const key=new T.DirectionalLight(0xfff4e6,2.0);key.position.set(3,5,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-2;key.shadow.camera.right=2;key.shadow.camera.top=3;key.shadow.camera.bottom=-2;key.shadow.bias=-.0008;key.shadow.normalBias=.015;scene.add(key);const fill=new T.DirectionalLight(0xd3eaff,.8);fill.position.set(-3,3,-2);scene.add(fill);
 const plane=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.12}));plane.rotation.x=-Math.PI/2;plane.position.y=.01;plane.receiveShadow=true;scene.add(plane);
 model=await loadModel();model.traverse(o=>{if(o.isMesh){for(const value of Object.values(o.material))if(value?.isTexture)assetTextures.add(value);o.castShadow=!o.name.startsWith('CUSTOM_')&&!o.name.startsWith('LED');o.receiveShadow=true;}});scene.add(model);for(const name of model.userData.defaultHidden||[]){const o=model.getObjectByName(name);o.scale.fromArray(o.userData.defaultScale||[1,1,1]);o.visible=false;}
 // Keep the display above user artwork; its material is replaceable through the public API.
 model.getObjectByName('DISPLAY_SCREEN').position.z=-.073;model.getObjectByName('DISPLAY_GLASS').position.z=-.070;
 observer=new ResizeObserver(resize);observer.observe(host);resize();setView();wire();$('#editor').disabled=false;$$('#viewer button').forEach(b=>b.disabled=false);$('#loadState').hidden=true;ready=true;
 on(renderer.domElement,'webglcontextlost',e=>{e.preventDefault();contextLost=true;$('#loadState').hidden=false;$('#loadState').innerHTML='<strong>The 3D view was paused by your device.</strong><p>Reload the page to restore your local draft.</p><button onclick="location.reload()">Reload studio</button>';});
 let restored=false;try{const saved=localStorage.getItem(KEY);if(saved){const {next,decoded}=await validateConfig(JSON.parse(saved));state=next;Object.assign(images,decoded);restored=true;}}catch{say('The previous draft could not be restored. You can load a saved JSON file.');}
 applyDesign();await changed();stats.loadMilliseconds=Math.round(performance.now()-start);if(restored)say('Your local draft has been restored.');
 window.PGCreator={version:MODEL,getConfiguration:snapshot,getRequestPayload:requestPayload,importConfiguration:importDesign,exportPNG:pngBlob,getStats:()=>({...stats,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,dpr:renderer.getPixelRatio()}),setScreenTexture(texture){if(!texture?.isTexture)throw new Error('Pass a THREE.Texture.');screenOwnedTexture?.dispose();screenOwnedTexture=null;const m=model.getObjectByName('DISPLAY_SCREEN').material;m.map=m.emissiveMap=texture;m.needsUpdate=true;invalidate();},async setScreenImage(file){const r=await rasterize(file);screenOwnedTexture?.dispose();screenOwnedTexture=new T.Texture(r.image);screenOwnedTexture.colorSpace=T.SRGBColorSpace;screenOwnedTexture.flipY=false;screenOwnedTexture.needsUpdate=true;const m=model.getObjectByName('DISPLAY_SCREEN').material;m.map=m.emissiveMap=screenOwnedTexture;m.needsUpdate=true;invalidate();},invalidate,dispose};
 // Read-only diagnostics for automated prototype checks, not a second state store.
 Object.defineProperty(window.PGCreator,'inspect',{value:()=>({state:structuredClone(state),visible:Object.fromEntries(Object.entries(EQUIPMENT).map(([k,[,n]])=>[k,model.getObjectByName(n).visible])),camera:camera.position.toArray(),color:model.getObjectByName('CENTRAL_CABINET').material.color.getHexString(),branding:Object.fromEntries(Object.entries(SURFACES).map(([k,n])=>[k,model.getObjectByName(n).visible]))})});
 }catch(e){renderer?.dispose();host.replaceChildren();$('#loadState').hidden=false;$('#loadState').innerHTML='<strong>The 3D studio could not load.</strong><p>Check your connection and enable hardware acceleration / WebGL, then try again.</p><button onclick="location.reload()">Reload studio</button>';throw e;}
}
