const{chromium}=require('playwright'),fs=require('fs'),assert=require('assert');
(async()=>{const browser=await chromium.launch({executablePath:'/tmp/pg-browsers/chromium-1161/chrome-linux/chrome',args:['--no-sandbox','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[],bad=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)bad.push(r.url())});page.on('request',r=>requests.push(r.url()));
await page.goto('http://127.0.0.1:8141/creator/');assert(!requests.some(x=>/app.js|\.glb/.test(x)));await page.click('#start');await page.waitForFunction(()=>!!window.PGCreator);await page.waitForFunction(()=>document.querySelector('#saveState').textContent==='Saved on this device');const initial=await page.evaluate(()=>PGCreator.getConfiguration());assert(/^PGC-DS-[A-F0-9]{20}$/.test(initial.configurationId));let baseline=await page.evaluate(()=>PGCreator.getStats());
const reqCount=requests.length;for(const color of ['red','black','white','orange','yellow','blue']){await page.click(`[data-color="${color}"]`);assert.equal((await page.evaluate(()=>PGCreator.inspect())).state.color,color);}
for(const key of ['card_reader','ticket_dispenser','banknote_acceptor','coin_acceptor','capsule_dispenser']){await page.check(`#equipment input[value="${key}"]`);assert((await page.evaluate(()=>PGCreator.inspect())).visible[key]);await page.uncheck(`#equipment input[value="${key}"]`);assert(!(await page.evaluate(()=>PGCreator.inspect())).visible[key]);}
await page.check('#equipment input[value="card_reader"]');await page.check('#equipment input[value="ticket_dispenser"]');assert.equal(requests.length,reqCount);
const camera0=(await page.evaluate(()=>PGCreator.inspect())).camera;await page.click('#zoomIn');assert.notDeepEqual((await page.evaluate(()=>PGCreator.inspect())).camera,camera0);await page.click('#resetCamera');const rect=await page.locator('#canvasHost').boundingBox();await page.mouse.move(rect.x+rect.width*.45,rect.y+rect.height*.4);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.65,rect.y+rect.height*.45,{steps:12});await page.mouse.up();assert.notDeepEqual((await page.evaluate(()=>PGCreator.inspect())).camera,camera0);
await page.click('#brandingSection summary');const svg='<svg xmlns="http://www.w3.org/2000/svg" width="480" height="240" viewBox="0 0 480 240"><rect x="5" y="5" width="470" height="230" rx="25" fill="#ff510b"/><text x="240" y="145" text-anchor="middle" font-family="Arial" font-weight="bold" font-size="62" fill="white">YOUR BRAND</text></svg>';
for(const side of ['front','left','right']){await page.click(`[data-surface="${side}"]`);await page.setInputFiles('#artUpload',{name:'brand-'+side+'.svg',mimeType:'image/svg+xml',buffer:Buffer.from(svg)});await page.waitForFunction(side=>!!PGCreator.inspect().state.branding[side],side);assert((await page.evaluate(()=>PGCreator.inspect())).branding[side]);}
await page.setInputFiles('#artUpload','progames/creator/textures/rear-art.png');await page.waitForFunction(()=>PGCreator.inspect().state.branding.right.fileName==='rear-art.png');await page.setInputFiles('#artUpload','creator-test-artifacts/upload.jpg');await page.waitForFunction(()=>PGCreator.inspect().state.branding.right.fileName==='upload.jpg');await page.setInputFiles('#artUpload',{name:'brand-right.svg',mimeType:'image/svg+xml',buffer:Buffer.from(svg)});await page.waitForFunction(()=>PGCreator.inspect().state.branding.right.fileName==='brand-right.svg');
await page.locator('#artX').evaluate(e=>{e.value='25';e.dispatchEvent(new Event('input',{bubbles:true}))});await page.locator('#artY').evaluate(e=>{e.value='-20';e.dispatchEvent(new Event('input',{bubbles:true}))});await page.locator('#artScale').evaluate(e=>{e.value='85';e.dispatchEvent(new Event('input',{bubbles:true}))});await page.locator('#artRotation').evaluate(e=>{e.value='30';e.dispatchEvent(new Event('input',{bubbles:true}))});let art=(await page.evaluate(()=>PGCreator.inspect())).state.branding.right;assert.equal(art.x,.25);assert.equal(art.y,-.2);assert.equal(art.scale,.85);assert.equal(art.rotation,30);await page.click('#resetArt');assert.equal((await page.evaluate(()=>PGCreator.inspect())).state.branding.right.rotation,0);
await page.setInputFiles('#artUpload',{name:'unsafe.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>')});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('unsupported'));assert.equal((await page.evaluate(()=>PGCreator.inspect())).state.branding.right.fileName,'brand-right.svg');
await page.locator('summary').filter({hasText:'CUSTOM DESIGN'}).click();await page.uncheck('#factoryGraphics');await page.uncheck('#ledLights');await page.click('#resetCamera');await page.locator('#viewer').screenshot({path:'creator-test-artifacts/custom-design.png'});
await page.locator('summary').filter({hasText:'PREVIEW & SAVE'}).click();const [jsonDl]=await Promise.all([page.waitForEvent('download'),page.click('#saveJSON')]);await jsonDl.saveAs('creator-test-artifacts/design.json');const config=JSON.parse(fs.readFileSync('creator-test-artifacts/design.json','utf8'));assert(config.design.branding.front.data.startsWith('data:image/png'));assert.equal(config.design.equipment.length,2);
const [pngDl]=await Promise.all([page.waitForEvent('download'),page.click('#downloadPNG')]);await pngDl.saveAs('creator-test-artifacts/design.png');assert(fs.readFileSync('creator-test-artifacts/design.png').subarray(1,4).toString()==='PNG');
await page.click('#request');await page.locator('#requestDialog').waitFor({state:'visible'});assert((await page.textContent('#requestSummary')).includes(config.configurationId));const mail=await page.getAttribute('#requestEmail','href');assert(mail.startsWith('mailto:office@progames.pl?'));assert(new URL(mail).searchParams.get('body').includes('Card reader'));await page.click('#requestDialog .close-dialog');
await page.click('#resetDesign');await page.click('#resetDialog button[value="reset"]');await page.waitForFunction(()=>PGCreator.inspect().state.equipment.length===0);assert.equal((await page.evaluate(()=>PGCreator.inspect())).state.equipment.length,0);assert.equal((await page.evaluate(()=>PGCreator.inspect())).state.branding.front,null);
await page.setInputFiles('#loadJSON','creator-test-artifacts/design.json');await page.waitForFunction(id=>PGCreator.getConfiguration().configurationId===id,config.configurationId);assert.deepEqual((await page.evaluate(()=>PGCreator.getConfiguration())).design,config.design);
const same=await page.evaluate(()=>PGCreator.getConfiguration());await page.setInputFiles('#loadJSON',{name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...config,design:{...config.design,branding:{front:{data:'https://invalid.example/a.png'}}}}))});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Invalid branding'));assert.deepEqual((await page.evaluate(()=>PGCreator.getConfiguration())).design,same.design);
await page.waitForFunction(()=>document.querySelector('#saveState').textContent==='Saved on this device');await page.reload();assert(!requests.slice(-3).some(x=>/\.glb/.test(x)));await page.click('#start');await page.waitForFunction(()=>!!window.PGCreator);assert.equal((await page.evaluate(()=>PGCreator.getConfiguration())).configurationId,config.configurationId);
await page.click('#fullPreview');assert(await page.locator('#viewer').evaluate(e=>e.classList.contains('full')));await page.keyboard.press('Escape');assert(!await page.locator('#viewer').evaluate(e=>e.classList.contains('full')));
const idle1=await page.evaluate(()=>PGCreator.getStats().frames);await page.waitForTimeout(750);const idle2=await page.evaluate(()=>PGCreator.getStats().frames);assert(idle2-idle1<=1,'Scene keeps rendering at rest');
const mem1=await page.evaluate(()=>PGCreator.getStats());for(let i=0;i<12;i++)await page.evaluate(c=>PGCreator.importConfiguration(c),config);const mem2=await page.evaluate(()=>PGCreator.getStats());assert(mem2.textures<=mem1.textures+1);assert(mem2.geometries<=mem1.geometries+1);
const responsive=[];for(const width of [320,390,768,1280,1920]){await page.setViewportSize({width,height:width<761?900:1080});await page.evaluate(()=>scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);const metrics=await page.locator('#viewer').boundingBox();responsive.push({width,viewer:metrics});await page.screenshot({path:`creator-test-artifacts/studio-${width}.png`});}
// Actual touch events: normal vertical scrolling remains available until rotation is explicitly enabled.
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:3});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto('http://127.0.0.1:8141/creator/');await m.click('#start');await m.waitForFunction(()=>!!window.PGCreator);assert.equal(await m.evaluate(()=>PGCreator.getStats().dpr),1.5);assert.equal(await m.locator('#canvasHost canvas').evaluate(e=>getComputedStyle(e).touchAction),'pan-y');await m.click('#touchMode');assert.equal(await m.locator('#canvasHost canvas').evaluate(e=>getComputedStyle(e).touchAction),'none');await m.click('#touchMode');assert.equal(await m.locator('#canvasHost canvas').evaluate(e=>getComputedStyle(e).touchAction),'pan-y');await m.screenshot({path:'creator-test-artifacts/mobile-touch.png'});
await mobile.close();assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);fs.writeFileSync('progames/creator/docs/test-results.json',JSON.stringify({status:'PASS',browser:'Chromium 134, software GPU in test environment',baseline,idleFrames:idle2-idle1,memoryBefore:mem1,memoryAfter:mem2,responsive,errors,bad,checks:['lazy load','all six colours','five optional modules on/off','no network on configuration change','orbit and zoom','PNG, JPG and three independent SVG uploads','position scale rotation reset','unsafe SVG rejection','PNG download','JSON round trip with graphics','stable content ID','malformed JSON rejection without state loss','local restore after reload','request payload and mailto without sending','full preview and Escape','idle rendering','texture/geometry stability after 12 imports','five viewport widths','touch rotation opt-in','mobile DPR cap']},null,2));console.log('PASS Creator integration and responsive checks');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
