import React,{lazy,Suspense,useState,useEffect,useRef} from 'react';
import {product,products,colors,presets} from '../products/doubleStrike.js';
import {load,save,portable,validate,readGraphic,newId} from './state.js';
import {t,lang} from './i18n.js';
const Viewer=lazy(()=>import('./Viewer.jsx'));
const download=(content,name,type)=>{const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function Request({state,close}){const product=products.find(p=>p.id===state.selectedProduct);const dialog=useRef(),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[countries,setCountries]=useState({}),[countryCode,setCountryCode]=useState({pl:'PL',en:'GB',es:'ES',de:'DE',fr:'FR'}[lang]),id=useRef(newId());useEffect(()=>{dialog.current.showModal();fetch('/assets/data/countries.json').then(r=>r.json()).then(setCountries).catch(()=>setStatus(t('error')))},[]);const names=new Intl.DisplayNames([lang],{type:'region'});
 async function submit(e){e.preventDefault();setBusy(true);setStatus('');const data=Object.fromEntries(new FormData(e.target));try{const payload={...data,dialCode:countries[data.country],countryName:names.of(data.country),product:product.name,configuration:product.name+' / '+state.bodyColor+' / '+state.graphicsPreset+' / '+state.ledMode,creatorConfiguration:portable(state),requestId:id.current,language:lang};const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});const result=await r.json();if(!r.ok||!result.ok)throw Error();setStatus(t('sent'));}catch{setStatus(t('error')+' office@progames.pl')}finally{setBusy(false)}}
 return <dialog className="creator-dialog" ref={dialog} onCancel={close}><form onSubmit={submit} onChange={()=>{id.current=newId()}}><div className="dialog-head"><h2>{t('request')}</h2><button type="button" onClick={close} aria-label={t('close')}>×</button></div><p className="muted">{product.name} · {state.bodyColor} · {state.configurationId.slice(0,8)}</p><div className="form-grid">{['name','company','email','phone'].map(k=><label key={k}>{t(k)}<input name={k} type={k==='email'?'email':k==='phone'?'tel':'text'} required={['name','email'].includes(k)} maxLength={{name:120,company:160,email:254,phone:30}[k]} autoComplete={{name:'name',company:'organization',email:'email',phone:'tel'}[k]}/></label>)}<label>{t('country')}<select name="country" required value={countryCode} onChange={e=>setCountryCode(e.target.value)}>{Object.keys(countries).sort((a,b)=>names.of(a).localeCompare(names.of(b),lang)).map(code=><option key={code} value={code}>{names.of(code)}</option>)}</select></label></div><label>{t('message')}<textarea name="message" rows="3" maxLength="5000"/></label><input name="website" tabIndex="-1" autoComplete="off" className="creator-trap" aria-hidden="true"/><p className="muted">{t('filesNote')}</p><p role="status">{status}</p><button className="creator-primary" disabled={busy||status===t('sent')||!Object.keys(countries).length}>{busy?'…':t('send')}</button></form></dialog>
}
export default function App(){const [state,setState]=useState(load),[section,setSection]=useState('color'),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[request,setRequest]=useState(false),[shareUrl,setShareUrl]=useState(''),api=useRef(),studio=useRef(),uploadToken=useRef(0);
 const product=products.find(p=>p.id===state.selectedProduct)||products[0];
 const set=patch=>setState(s=>({...s,...patch}));
 useEffect(()=>{try{const hash=new URLSearchParams(location.hash.slice(1)).get('c');if(hash){if(hash.length>16000)throw Error();setState(validate(JSON.parse(decodeURIComponent(atob(hash)))));history.replaceState(null,'',location.pathname)}}catch{setStatus(t('error'))}},[]);
 useEffect(()=>{try{save(state)}catch{setStatus(t('storageError'))}},[state]);
 const selectZone=id=>{setSection('graphics');const z=product.decalZones.find(z=>z.id===id);set({selectedGraphicZone:id,cameraPreset:z.camera});api.current?.view(z.camera)};
 const g=state.customGraphics[state.selectedGraphicZone]||{mode:'factory',scale:1,x:0,y:0,rotation:0,fit:'fit'};
 const edit=(patch,id=state.selectedGraphicZone)=>setState(s=>({...s,customGraphics:{...s.customGraphics,[id]:{...(s.customGraphics[id]||{mode:'factory',scale:1,x:0,y:0,rotation:0,fit:'fit'}),...patch}}}));
 async function upload(e){const file=e.target.files?.[0],zone=state.selectedGraphicZone,token=++uploadToken.current;if(!file)return;try{const result=await readGraphic(file);if(token===uploadToken.current)edit(result,zone);setStatus('')}catch{setStatus(t('uploadError'))}e.target.value=''}
 async function share(){try{const clean=portable(state);clean.customGraphics=Object.fromEntries(Object.entries(clean.customGraphics).filter(([,g])=>g.mode!=='custom'));const url=new URL((lang==='en'?'':'/'+lang)+'/creator/config/'+state.configurationId,location.origin);url.hash='c='+btoa(encodeURIComponent(JSON.stringify(clean)));setShareUrl(url.href);await navigator.clipboard?.writeText(url.href);setStatus(t('shareNote'))}catch{setStatus(t('shareNote'))}}
 const exportConfig=()=>download(JSON.stringify({...state,schemaVersion:1},null,2),'progames-'+state.configurationId+'.json','application/json');
 async function importConfig(e){try{const file=e.target.files[0];if(!file||file.size>4*1024*1024)throw Error();setState(validate(JSON.parse(await file.text())));setStatus('')}catch{setStatus(t('error'))}e.target.value=''}
 const preview=()=>{try{if(!api.current)throw Error();const a=document.createElement('a');a.href=api.current.snapshot();a.download='progames-'+state.configurationId.slice(0,8)+'.png';a.click()}catch{setStatus(t('error'))}};
 return <main className="creator" id="creator"><div className="creator-title"><div><p className="creator-eyebrow">DESIGNED BY PRO GAMES. CONFIGURED BY YOU.</p><h1>PRO GAMES <span>CREATOR</span></h1></div><p>{t('subtitle')}</p></div><div className="creator-studio" ref={studio}><section className="creator-stage" aria-label="3D studio"><div className="stage-label"><span>01 / {product.name.toUpperCase()}</span><span>{product.category}</span></div><Suspense fallback={null}><Viewer key={product.id} product={product} state={state} api={api} graphics={section==='graphics'} onZone={selectZone} onReady={()=>setLoading(false)} onError={()=>{setLoading(false);setFailed(true)}}/></Suspense>{loading&&<div className="creator-loading" role="status"><b>PRO GAMES CREATOR</b><progress/><p>{t('loading')}</p></div>}{failed&&<div className="creator-fallback stage-fallback" role="status"><img src={product.previewPath} alt={product.name}/><p>{t('fallback')}</p></div>}<div className="camera-bar">{['front','left','right','back','threeQuarter'].map(k=><button key={k} aria-pressed={state.cameraPreset===k} onClick={()=>{set({cameraPreset:k});api.current?.view(k)}}>{t(k)}</button>)}<button aria-label={t('view')} title={t('view')} onClick={()=>api.current?.view('threeQuarter')}>↺</button><button aria-label={t('fullscreen')} title={t('fullscreen')} onClick={()=>{const p=document.fullscreenElement?document.exitFullscreen():studio.current.requestFullscreen?.();p?.catch(()=>setStatus(t('error')))}}>⛶</button></div><div className="stage-caption"><span>{t('hint')}</span><span>{t('demo')}</span></div></section><aside className="creator-sidebar"><div className="studio-heading"><span>{product.name.toUpperCase()}</span><span className="creator-badge">3D STUDIO</span></div>{['model','color','graphics','led','options','summary'].map((key,i)=><section className={'creator-section '+(section===key?'is-open':'')} key={key}><button className="section-toggle" aria-expanded={section===key} aria-controls={'panel-'+key} onClick={()=>setSection(section===key?'':key)}><span className="section-number">0{i+1}</span><span>{t(key)}</span><span>{section===key?'−':'+'}</span></button><div id={'panel-'+key} hidden={section!==key} className="section-content">
{key==='model'&&<label>{t('model')}<select value={state.selectedProduct} onChange={e=>{const p=products.find(p=>p.id===e.target.value);setLoading(true);setFailed(false);setState({...p.defaultConfiguration,customGraphics:{},configurationId:newId()})}}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><img className="model-thumb" src={product.previewPath} alt={product.name}/></label>}
{key==='color'&&<><div className="color-grid">{colors.map(c=><button className="color-swatch" key={c} style={{'--swatch':c}} aria-label={c} aria-pressed={state.bodyColor===c} onClick={()=>set({bodyColor:c})}>{state.bodyColor===c?'✓':''}</button>)}</div><label className="custom-color">{t('custom')}<input aria-label={t('color')} type="color" value={state.bodyColor} onChange={e=>set({bodyColor:e.target.value})}/><code>{state.bodyColor.toUpperCase()}</code></label></>}
{key==='graphics'&&<><label>{t('graphics')}<select value={state.graphicsPreset} onChange={e=>set({graphicsPreset:e.target.value})}>{presets.map(p=><option key={p}>{p}</option>)}</select></label><div className="zone-grid">{product.decalZones.map(z=><button key={z.id} aria-pressed={state.selectedGraphicZone===z.id} onClick={()=>selectZone(z.id)}>{t(z.id)}</button>)}</div><label className="upload-label">＋ {t('upload')}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><small>PNG / JPG / WEBP · MAX 5 MB</small>{g.name&&<p className="file-name">{g.name}</p>}<div className="inline-actions"><button onClick={()=>edit({mode:'none',src:undefined,name:'',scale:1,x:0,y:0,rotation:0,fit:'fit'})}>{t('remove')}</button><button onClick={()=>edit({mode:'factory',src:undefined,name:'',scale:1,x:0,y:0,rotation:0,fit:'fit'})}>{t('factory')}</button></div>{g.mode==='custom'&&<div className="graphic-controls">{['scale','x','y','rotation'].map(k=><label key={k}>{t(k)}<output>{g[k]}</output><input type="range" min={k==='scale'?.1:k==='rotation'?-180:-1} max={k==='scale'?3:k==='rotation'?180:1} step={k==='rotation'?1:.01} value={g[k]} onChange={e=>edit({[k]:Number(e.target.value)})}/></label>)}<div className="inline-actions">{['fit','fill'].map(v=><button key={v} aria-pressed={g.fit===v} onClick={()=>edit({fit:v})}>{t(v)}</button>)}<button onClick={()=>edit({x:0,y:0})}>{t('center')}</button><button onClick={()=>edit({scale:1,x:0,y:0,rotation:0,fit:'fit'})}>{t('reset')}</button></div></div>}</>}
{key==='led'&&<div className="choice-stack">{['Original RGB','White','Blue','Red','Rainbow'].map(v=><button key={v} aria-pressed={state.ledMode===v} onClick={()=>set({ledMode:v})}><i style={{background:{White:'#cdd2d6',Blue:'#218aff',Red:'#ff344d'}[v]||'linear-gradient(90deg,#f9607e,#7fedf0,#f9d868)'}}/>{v}<span>{state.ledMode===v?'✓':''}</span></button>)}</div>}
{key==='options'&&product.availableOptions.map(k=><label className="option-row" key={k}><input type="checkbox" checked={state.selectedOptions.includes(k)} onChange={e=>set({selectedOptions:e.target.checked?[...state.selectedOptions,k]:state.selectedOptions.filter(x=>x!==k)})}/>{t(k)}</label>)}
{key==='summary'&&<><dl><dt>{t('model')}</dt><dd>{product.name}</dd><dt>{t('color')}</dt><dd>{state.bodyColor}</dd><dt>{t('graphics')}</dt><dd>{state.graphicsPreset}</dd><dt>{t('led')}</dt><dd>{state.ledMode}</dd><dt>{t('options')}</dt><dd>{state.selectedOptions.map(t).join(', ')||t('none')}</dd></dl>{Object.entries(state.customGraphics).map(([z,g])=><p className="muted" key={z}>{t(z)}: {g.name||t(g.mode==='none'?'none':'factory')}</p>)}<code className="configuration-id">{state.configurationId}</code></>}
</div></section>)}<div className="creator-actions"><button className="creator-primary" onClick={()=>setRequest(true)}>{t('request')} <span>↗</span></button><div className="inline-actions"><button onClick={preview} disabled={loading||failed}>{t('save')} ↓</button><button onClick={share}>{t('share')} ↗</button></div><details className="file-actions"><summary>JSON · {t('export')} / {t('import')}</summary><button onClick={exportConfig}>{t('export')}</button><label>{t('import')}<input type="file" accept="application/json,.json" onChange={importConfig}/></label></details><p className="save-note">● {t('saved')}</p>{status&&<p role="status" className="creator-status">{status}</p>}{shareUrl&&<label>{t('share')}<input readOnly value={shareUrl} onFocus={e=>e.target.select()}/><small>{t('shareNote')}</small></label>}</div></aside></div>{request&&<Request state={state} close={()=>setRequest(false)}/>}</main>
}
