import React,{useEffect,useMemo,useRef,useState,Suspense,Component} from 'react';
import {Canvas,useThree,useFrame} from '@react-three/fiber';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {buildMachine} from './model.js';
import {makeTexture} from './textures.js';
import {t} from './i18n.js';
const cameraPositions=product=>({front:[0,1.55,4.4],left:[-4,1.65,.12],right:[4,1.65,.12],back:[0,1.55,-4.4],threeQuarter:product.cameraPosition});
function Scene({product,state,onZone,graphics,api,onReady,onError}){
 const positions=cameraPositions(product);
 const {camera,gl,scene,invalidate}=useThree(),controls=useRef(),motion=useRef(null),machine=useMemo(()=>product.modelPath?new T.Group():buildMachine(),[]),active=useRef(machine),[version,setVersion]=useState(0);
 useEffect(()=>{let disposed=false;const env=new RoomEnvironment(),pm=new T.PMREMGenerator(gl),target=pm.fromScene(env,.04);scene.environment=target.texture;env.dispose();pm.dispose();
  if(product.modelPath)new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).load(product.modelPath,gltf=>{if(disposed)return;const obj=gltf.scene;const missing=[...product.configurableMeshes].filter(n=>!obj.getObjectByName(n));if(missing.length){onError();return}obj.traverse(o=>{if(!o.isMesh)return;if(o.name.startsWith('decal_')){o.material=o.material.clone();o.material.transparent=true;o.material.depthWrite=false;o.material.polygonOffset=true;o.material.polygonOffsetFactor=-2;}if(o.name.startsWith('screen_')){o.material=o.material.clone();const c=document.createElement('canvas');c.width=256;c.height=120;const ctx=c.getContext('2d');ctx.fillStyle='#100409';ctx.fillRect(0,0,256,120);ctx.fillStyle='#ff2547';ctx.font='italic 90px monospace';ctx.textAlign='center';ctx.fillText(o.name==='screen_main'?'777':'649',128,94);const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;o.material.map=tx;o.material.emissive.set('#ff6a6a');o.material.emissiveMap=tx;o.material.emissiveIntensity=.35;}});machine.clear();machine.add(obj);active.current=machine;setVersion(v=>v+1);onReady();invalidate()},undefined,onError);
  else onReady();return()=>{disposed=true;target.dispose();scene.environment=null;};
 },[]);
 useEffect(()=>{const c=new OrbitControls(camera,gl.domElement);c.target.set(0,1.3,.10);c.minDistance=2.4;c.maxDistance=6.4;c.maxPolarAngle=Math.PI*.51;c.minPolarAngle=.15;c.enableDamping=true;c.dampingFactor=.1;c.panSpeed=.35;c.addEventListener('start',()=>motion.current=null);c.addEventListener('change',()=>{c.target.x=T.MathUtils.clamp(c.target.x,-.6,.6);c.target.y=T.MathUtils.clamp(c.target.y,.65,1.9);c.target.z=T.MathUtils.clamp(c.target.z,-.5,.5);invalidate()});controls.current=c;camera.position.set(...product.cameraPosition).multiplyScalar(window.matchMedia('(prefers-reduced-motion: reduce)').matches?1:.90);motion.current={p:new T.Vector3(...product.cameraPosition),target:new T.Vector3(0,1.3,.10)};invalidate();return()=>c.dispose()},[]);
 useEffect(()=>{motion.current={p:new T.Vector3(...(positions[state.cameraPreset]||positions.threeQuarter)),target:new T.Vector3(0,1.3,.1)};invalidate()},[state.cameraPreset]);
 useEffect(()=>{let ledIndex=0;active.current.traverse(o=>{if(!o.isMesh)return;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(product.colorMaterials.includes(m.name))m.color.set(state.bodyColor);if(product.ledZones.includes(m.name)){if(!o.userData.ledClone){o.material=m.clone();o.userData.ledClone=true;}const lm=o.material;const hex={White:'#f4f5ff',Blue:'#328bff',Red:'#ff293f'}[state.ledMode]||'#68daff';lm.color.set(hex);if(state.ledMode==='Original RGB')lm.color.set(['#71d8ff','#ff79bb','#7bffbe','#ffffff'][ledIndex++%4]);if(state.ledMode==='Rainbow')lm.color.setHSL((ledIndex++*.071)%1,.8,.65);lm.emissive.copy(lm.color);lm.emissiveIntensity=.8}}});
 invalidate();},[state.bodyColor,state.ledMode,version]);
 useEffect(()=>{let cancelled=false;Promise.all(product.decalZones.map(async z=>{const tx=await makeTexture(z,state);if(cancelled){tx.dispose();return}const mesh=active.current.getObjectByName(z.mesh);if(mesh){mesh.material.map?.dispose();mesh.material.map=tx;mesh.material.needsUpdate=true;mesh.userData.zone=z.id}else tx.dispose()})).then(invalidate).catch(onError);invalidate();return()=>{cancelled=true};},[state.graphicsPreset,state.customGraphics,version]);
 useEffect(()=>{for(const [option,names] of Object.entries(product.optionMeshes||{}))for(const name of names){const mesh=active.current.getObjectByName(name);if(mesh)mesh.visible=state.selectedOptions.includes(option)}invalidate()},[state.selectedOptions,version]);
 useFrame((_,dt)=>{const c=controls.current;if(!c)return;if(motion.current){camera.position.lerp(motion.current.p,1-Math.exp(-dt*6));c.target.lerp(motion.current.target,1-Math.exp(-dt*6));if(camera.position.distanceTo(motion.current.p)<.006)motion.current=null;invalidate()}c.update()});
 useEffect(()=>{api.current={view:(name)=>{motion.current={p:new T.Vector3(...positions[name]),target:new T.Vector3(0,1.3,.1)};invalidate()},snapshot:()=>{const old=gl.getSize(new T.Vector2()),dpr=gl.getPixelRatio();try{gl.setPixelRatio(1);gl.setSize(2000,Math.round(2000*old.y/old.x),false);gl.render(scene,camera);return gl.domElement.toDataURL('image/png')}finally{gl.setPixelRatio(dpr);gl.setSize(old.x,old.y,false);invalidate()}}};return()=>api.current=null},[]);
 useEffect(()=>()=>{machine.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose()}}})},[]);
 return <><hemisphereLight args={['#ffffff','#7c8894',2]}/><directionalLight position={[3,5,4]} intensity={3.2} castShadow shadow-mapSize={window.matchMedia('(max-width: 760px)').matches?[512,512]:[1024,1024]} shadow-camera-left={-2} shadow-camera-right={2} shadow-camera-top={3} shadow-camera-bottom={-2} shadow-bias={-.001}/><directionalLight position={[-3,3,-2]} intensity={2}/><primitive object={machine} onClick={e=>{if(graphics&&e.object.userData.zone){e.stopPropagation();onZone(e.object.userData.zone)}}}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.002,0]} receiveShadow><planeGeometry args={[200,200]}/><meshStandardMaterial color="#ebedf0" roughness={.9}/></mesh>{graphics&&product.decalZones.map(z=><mesh key={z.id} position={[z.position[0],z.position[1],z.position[2]+.035]} onClick={e=>{e.stopPropagation();onZone(z.id)}}><sphereGeometry args={[.021,12,8]}/><meshBasicMaterial color={state.selectedGraphicZone===z.id?'#006cff':'#ffffff'} depthTest={false}/></mesh>)}</>;
}
class Boundary extends Component{state={error:false};static getDerivedStateFromError(){return {error:true}}componentDidCatch(){this.props.onError()}render(){return this.state.error?this.props.fallback:this.props.children}}
export default function Viewer(props){const fallback=<div className="creator-fallback"><img src={props.product.previewPath} alt={props.product.name}/><p>{t('fallback')}</p></div>;return <Boundary onError={props.onError} fallback={fallback}><Canvas shadows dpr={window.matchMedia('(max-width: 760px)').matches?1:[1,1.5]} frameloop="demand" camera={{position:props.product.cameraPosition,fov:40,near:.1,far:100}} gl={{antialias:true,preserveDrawingBuffer:true,alpha:false}} fallback={fallback} onCreated={({gl})=>{gl.setClearColor('#ebedf0');gl.domElement.setAttribute('aria-label','Double Strike 3D');gl.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();props.onError()});}}><Scene {...props}/></Canvas></Boundary>}
