window.PRODUCT_PL={
  "monster-3in1-ticket": {
    "desc": "Automat rozrywkowy 3 w 1: Boxer, Kicker i Hammer\n\nTen innowacyjny automat 3 w 1 łączy trzy popularne gry mierzące siłę w jednym kompaktowym urządzeniu — Boxer, Kicker i Hammer.\n\nGracze mogą sprawdzić swoją siłę, wybierając uderzanie pięścią, kopanie lub uderzanie młotem — wszystko w jednej trwałej i przyciągającej wzrok obudowie.\n\nAutomat wyróżnia się nowoczesnym wzornictwem z oświetleniem LED oraz wysokiej jakości czujnikami zapewniającymi dokładny pomiar wyniku\n\nIdealny do barów, centrów rozrywki i na wydarzenia — zapewnia maksimum rozrywki, jednocześnie oszczędzając miejsce."
  },
  "monster-3in1": {
    "desc": "Automat rozrywkowy 3 w 1: Boxer, Kicker i Hammer\n\nTen innowacyjny automat 3 w 1 łączy trzy popularne gry mierzące siłę w jednym kompaktowym urządzeniu — Boxer, Kicker i Hammer.\n\nGracze mogą sprawdzić swoją siłę, wybierając uderzanie pięścią, kopanie lub uderzanie młotem — wszystko w jednej trwałej i przyciągającej wzrok obudowie.\n\nAutomat wyróżnia się nowoczesnym wzornictwem z oświetleniem LED oraz wysokiej jakości czujnikami zapewniającymi dokładny pomiar wyniku\n\nIdealny do barów, centrów rozrywki i na wydarzenia — zapewnia maksimum rozrywki, jednocześnie oszczędzając miejsce."
  },
  "double-hit": {
    "desc": "Dwa ekscytujące wyzwania w jednym kompaktowym automacie, z intensywnym oświetleniem LED, które dodatkowo przyciąga uwagę. Naciśnij górny przycisk Start, aby zwolnić gruszkę bokserską i sprawdzić swoją siłę, lub dolny przycisk, aby kopnąć piłkę i pokazać swoje umiejętności. Podwójna akcja w jednej grze!"
  },
  "double-hit-gift": {
    "desc": "Ten wszechstronny automat oferuje trzy ekscytujące wyzwania: boksowanie, kopanie i funkcję nagród — wszystko w jednej kompaktowej konstrukcji. Intensywne oświetlenie LED dodatkowo przyciąga uwagę, a gracze mogą pokazać siłę i umiejętności, uderzając gruszkę bokserską lub kopiąc piłkę, oraz zdobywać specjalne nagrody, które zwiększają motywację i emocje. Potrójna akcja w jednej grze!"
  },
  "double-hit-kids": {
    "desc": "Ten automat łączy dwie ekscytujące gry w jednej: boksowanie i kopanie! Zaprojektowany specjalnie dla młodszych graczy, zapewnia podwójną zabawę w jednym urządzeniu i idealnie nadaje się do obiektów rodzinnych."
  },
  "double-hit-kids-gift": {
    "desc": "Ten automat łączy trzy zabawy w jednej: boksowanie, kopanie i funkcję nagród! Zaprojektowany dla młodych graczy, przyciąga dzieci ekscytującymi wyzwaniami i intensywnym oświetleniem LED, dzięki czemu doskonale pasuje do obiektów rodzinnych."
  },
  "double-strike": {
    "desc": "Dwa ekscytujące wyzwania w jednym kompaktowym automacie, z intensywnym oświetleniem LED, które dodatkowo przyciąga uwagę. Naciśnij górny przycisk Start, aby zwolnić gruszkę bokserską i sprawdzić swoją siłę, lub dolny przycisk, aby kopnąć piłkę i pokazać swoje umiejętności. Podwójna akcja w jednej grze!"
  },
  "joker": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "pow-boxer": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "champion": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "easy": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "cyber-punch": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "gladiator": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "mma": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "black-jack": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "super-hero": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "power-black": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "poison-squad": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "hacker": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "strongman": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "viking": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "disco": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "matte-airbrushed": {
    "desc": "Matte Airbrushed to propozycja dla obiektów, które stawiają na bardziej stonowaną, premium stylistykę. Matowe czarne wykończenie nadaje automatom nowoczesny charakter, a do wyboru są warianty Standard, Combat i Double Hit. Wybierz wersję, a nasz zespół pomoże dobrać wyposażenie i konfigurację odpowiednią do Twojego obiektu."
  },
  "boxer-combat": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "boxer-fist": {
    "desc": "WIELOOSOBOWY AUTOMAT BOKSERSKI\n\nBoxer Fist to nasz nowy, ekscytujący wieloosobowy automat bokserski, stworzony, by bawić i stawiać wyzwania grupom w salonach gier, rodzinnych centrach rozrywki i innych obiektach rozrywkowych. Przyciągające wzrok oświetlenie LED, nowoczesne naklejki i solidna konstrukcja zachęcają do rywalizacji i kolejnych rozgrywek."
  },
  "boxer-ring": {
    "desc": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek."
  },
  "boxer-combat-kids": {
    "desc": "Kids Combat, jeden z najnowszych modeli w naszej ofercie, zapewnia młodszym graczom ekscytującą i bezpieczną zabawę bokserską. Dzięki wyrazistemu wzornictwu i udoskonalonym funkcjom idealnie nadaje się do salonów gier i obiektów rodzinnych."
  },
  "boxer-kids": {
    "desc": "Ten automat został zaprojektowany specjalnie dla młodszych graczy i zapewnia bezpieczny oraz przyjemny sposób na poznanie emocji gry bokserskiej. Dzięki jaskrawym kolorom i angażującej rozgrywce doskonale sprawdza się w miejscach nastawionych na rodziny."
  },
  "boxer-flash-gift": {
    "desc": "Boxer Flash Gift urozmaica klasyczne wyzwanie bokserskie funkcją zdobywania nagród. Oferuje jasne oświetlenie LED i angażującą rozgrywkę."
  },
  "hammer": {
    "desc": "To klasyczna gra mierząca siłę, w której gracze starają się uderzyć jak najmocniej. Idealna do parków rozrywki, salonów gier i rodzinnych centrów rozrywki (FEC), ta ponadczasowa gra zapewnia zabawę i rywalizację, a intensywne oświetlenie LED przyciąga tłumy."
  },
  "kicker": {
    "desc": "Ten automat oferuje ekscytującą, dynamiczną grę dla osób, które chcą sprawdzić siłę i celność kopnięcia. Idealny zarówno dla dzieci, jak i dorosłych, stanowi świetne uzupełnienie salonów gier, barów sportowych i rodzinnych centrów rozrywki."
  },
  "boxer-flash": {
    "desc": "Boxer Flash łączy klasyczną rywalizację na wynik z wyrazistą, nowoczesną stylistyką. Kilka wariantów kolorystycznych ułatwia dopasowanie automatu do charakteru salonu gier, baru, klubu lub strefy rozrywki. Wybierz kolor i wyposażenie, a nasz dział sprzedaży przygotuje konfigurację dopasowaną do Twojego obiektu."
  },
  "boxer-gift": {
    "desc": "Boxer Gift urozmaica klasyczne wyzwanie bokserskie funkcją zdobywania nagród. Oferuje jasne oświetlenie LED i angażującą rozgrywkę."
  },
  "bouncy-castles-xs": {
    "desc": "Małe dmuchane zamki dla dzieci\n\nDmuchane zamki Mini XS to fantastyczna atrakcja dla najmłodszych gości Twojego wydarzenia! Te kolorowe dmuchańce od razu przyciągają uwagę dzieci i szybko stają się ich ulubionym miejscem zabawy.\n\nDzieci wiedzą, że w środku czeka na nie nieograniczona zabawa. W kompaktowym dmuchanym zamku mogą godzinami skakać, bawić się i spożytkować energię. Niektóre z naszych dmuchańców dla dzieci mają również wbudowane zjeżdżalnie.\n\nNasze małe dmuchane zamki zawsze cieszą się ogromnym powodzeniem wśród dzieci!"
  },
  "air-hockey-golden": {
    "desc": "Cymbergaj Golden to nowa wersja naszego bestsellerowego modelu do wnętrz.\n\nStół Golden wyróżnia się dopracowanym, eleganckim wzornictwem, które harmonijnie pasuje do każdego wnętrza. Subtelna kolorystyka w połączeniu z gustownymi złotymi akcentami nadaje mu ponadczasowy wygląd, który nigdy nie wychodzi z mody. Ten stół to nie tylko źródło rozrywki, ale także stylowy dodatek do każdego pokoju gier lub przestrzeni wypoczynkowej.\n\nSolidna konstrukcja sprawdzona przez ponad 20 lat doświadczenia. Nowoczesne oprogramowanie umożliwia łatwą personalizację różnych ustawień.\n\nUwaga:\n\nPrzedstawiona lampa jest wyposażeniem opcjonalnym — nie jest sprzedawana w standardzie."
  },
  "air-hockey-arctic": {
    "desc": "AIR HOCKEY ARCTIC to w 100% wodoodporne urządzenie, które może być używane przez cały rok na zewnątrz, tak samo jak wewnątrz. To jeden z najpopularniejszych automatów. Solidna konstrukcja sprawdzona przez ponad 20 lat doświadczenia. Nowoczesne oprogramowanie pozwala łatwo personalizować różne ustawienia."
  },
  "air-hockey-matrix": {
    "desc": "Poznaj nasz zupełnie nowy cymbergaj Matrix! Wyświetlacz LED nie tylko świetnie wygląda — przekazuje też informacje o przebiegu gry, pokazując „SCORE!” po zdobyciu gola i współczujące „OH NO!”, gdy stracisz bramkę. Liczniki na obu końcach informują o pozostałym czasie, a cały wyświetlacz zmienia wygląd, kolory i pulsuje w idealnej synchronizacji z grą. Konfigurowalne ustawienia operatora pozwalają dopasować stół do własnych potrzeb, a pompa powietrza o mocy 260 W tworzy poduszkę powietrzną nad polem gry, zapewniając największe prędkości.\n\nCymbergaj istnieje od dawna, a duże przełomy we wzornictwie lub funkcjonalności zdarzają się rzadko. Teraz Matrix wyznacza nowy poziom dzięki zintegrowanym wyświetlaczom i systemom LED. Jeśli szukasz naprawdę spektakularnej głównej atrakcji do swojego lokalu — lub nawet prywatnego pokoju gier — wybierz czerwoną pigułkę i wejdź do Matrixa już teraz!"
  },
  "basketball-compact": {
    "desc": "Nowy automat do koszykówki firmy WIK. Kompaktowe wymiary umożliwiają przejazd przez drzwi o szerokości 80 cm. Wysokość dostosowywana w zakresie 248–310 cm."
  },
  "basketball": {
    "desc": "Nasze odporne na warunki atmosferyczne automaty do koszykówki mogą być używane na zewnątrz przez cały rok. Gra ma cztery poziomy trudności i jest dostarczana z zestawem pięciu piłek. W zależności od wybranego trybu kosz może się poruszać.\n\nMontaż i transport są bardzo łatwe.\n\nKoszykówka to gra dla osób w każdym wieku, uwielbiana zarówno przez dzieci, jak i dorosłych. Gracze mogą grać w grupie i rywalizować o najlepszy wynik (opcja łączenia urządzeń). To wysokiej jakości, trwały automat. WIK jest liderem produkcji automatów do koszykówki z wieloletnim doświadczeniem. To atrakcja lubiana przez publiczność, która nie przestaje dostarczać zabawy."
  },
  "kids-basketball": {
    "desc": "Kids Basketball to kompaktowa wersja automatu koszykarskiego przygotowana z myślą o młodszych graczach. Kolorowa i czytelna forma dobrze wpisuje się w rodzinne strefy rozrywki oraz miejsca nastawione na dzieci. Skontaktuj się z naszym zespołem, aby potwierdzić aktualną konfigurację i dostępność."
  },
  "kiddie-ride": {
    "desc": "Kiddie Ride to klasyczna atrakcja dla najmłodszych, dobrze pasująca do rodzinnych stref rozrywki, galerii handlowych i innych obiektów odwiedzanych przez rodziny. Dostępne wzory i konfiguracje mogą się zmieniać, dlatego aktualną ofertę potwierdzi nasz dział sprzedaży."
  },
  "cyberdart": {
    "desc": "Cyberdart to elektroniczny automat do gry w rzutki, który łączy klasyczną rywalizację z czytelnym panelem wyników i samoobsługową formą rozgrywki. To uniwersalna atrakcja do salonów gier, pubów, klubów i stref rozrywki. Aktualną konfigurację i dostępność potwierdzi nasz dział sprzedaży."
  },
  "hammer-2026": {
    "desc": "Nowa odsłona gry siłowej Hammer na 2026 rok — wysoka, podświetlana konstrukcja z wyraźnie wydzieloną strefą uderzenia. Pionowa forma sprawia, że automat świetnie prezentuje się w salonach gier, parkach rozrywki i innych obiektach entertainment.\n\nModel dostępny jest w pokazanym, wielokolorowym wykończeniu. Skontaktuj się z naszym zespołem, aby dobrać konfigurację działania i wyposażenie opcjonalne do Twojego obiektu. Ostateczne dane techniczne potwierdzimy w przygotowanej ofercie."
  },
  "win-a-toy": {
    "desc": "Win a toy łączy emocje klasycznego automatu bokserskiego z mechaniką nagród. Podświetlana obudowa integruje cel bokserski, wyświetlacz wyniku oraz widoczną strefę z nagrodami, dzięki czemu urządzenie mocno przyciąga uwagę w salonach gier i obiektach rozrywkowych.\n\nWybierz jeden z ośmiu dostępnych kolorów obudowy i zaznacz wyposażenie, które mamy uwzględnić w ofercie. Sposób wydawania nagród, system płatności oraz finalne parametry techniczne ustalamy indywidualnie z działem sprzedaży."
  },
  "leader-rank": {
    "desc": "Boxer Leader Rank to wyrazista konstrukcja na 2026 rok z dużym frontowym wyświetlaczem, podświetlanymi detalami i wysoko umieszczonym celem bokserskim. Grafika inspirowana rywalizacją nadaje urządzeniu mocny charakter i sprawia, że dobrze wyróżnia się w salonie gier lub nowoczesnym obiekcie rozrywkowym.\n\nWybierz jeden z siedmiu kolorów obudowy i skonfiguruj wyposażenie do zapytania ofertowego. Funkcje gry, specyfikację wyświetlacza oraz ostateczne dane techniczne potwierdzimy w ofercie."
  }
};
window.PG_PL={
  "labels": {
    "3-IN-1 / TICKET": "3 W 1 / TICKETY",
    "3-IN-1": "3 W 1",
    "BOXER + KICKER": "BOXER + KICKER",
    "BOXER + KICKER + PRIZE": "BOXER + KICKER + NAGRODY",
    "KIDS / BOXER + KICKER": "DLA DZIECI / BOXER + KICKER",
    "KIDS / BOXER + KICKER + PRIZE": "DLA DZIECI / BOXER + KICKER + NAGRODY",
    "DOUBLE CHALLENGE": "PODWÓJNE WYZWANIE",
    "BOXER STANDARD": "BOXER STANDARD",
    "MATTE / AIRBRUSHED": "MATOWY / AIRBRUSH",
    "BOXER PREMIUM": "BOXER PREMIUM",
    "MULTIPLAYER BOXER": "BOXER WIELOOSOBOWY",
    "PREMIUM KIDS": "PREMIUM DLA DZIECI",
    "BOXER KIDS": "BOXER DLA DZIECI",
    "BOXER PREMIUM / PRIZE": "BOXER PREMIUM / NAGRODY",
    "HAMMER": "MŁOT",
    "KICKER": "KICKER",
    "BOXER / PRIZE": "BOXER / NAGRODY",
    "DISTRIBUTED / INFLATABLES": "DYSTRYBUCJA / DMUCHAŃCE",
    "DISTRIBUTED / AIR HOCKEY": "DYSTRYBUCJA / AIR HOCKEY",
    "DISTRIBUTED / BASKETBALL": "DYSTRYBUCJA / KOSZYKÓWKA",
    "DISTRIBUTED / KIDS BASKETBALL": "DYSTRYBUCJA / KOSZYKÓWKA DLA DZIECI",
    "DISTRIBUTED MACHINE": "URZĄDZENIE DYSTRYBUOWANE",
    "STRENGTH GAME": "GRA SIŁOWA"
  },
  "specs": {
    "3-in-1 Amusement Machine: Boxer, Kicker & Hammer": "Automat rozrywkowy 3 w 1: Boxer, Kicker i Hammer",
    "This innovative 3-in-1 arcade machine combines three popular strength-testing games in one compact unit — Boxer, Kicker, and Hammer.": "Ten innowacyjny automat 3 w 1 łączy trzy popularne gry mierzące siłę w jednym kompaktowym urządzeniu — Boxer, Kicker i Hammer.",
    "Players can test their power by choosing between punching, kicking, or hammering modes, all integrated into a single durable and eye-catching cabinet.": "Gracze mogą sprawdzić swoją siłę, wybierając uderzanie pięścią, kopanie lub uderzanie młotem — wszystko w jednej trwałej i przyciągającej wzrok obudowie.",
    "The machine features a modern design with LED lighting, high-quality sensors for accurate scoring": "Automat wyróżnia się nowoczesnym wzornictwem z oświetleniem LED oraz wysokiej jakości czujnikami zapewniającymi dokładny pomiar wyniku",
    "Perfect for bars, amusement centers, and events, it offers maximum entertainment value while saving space.": "Idealny do barów, centrów rozrywki i na wydarzenia — zapewnia maksimum rozrywki, jednocześnie oszczędzając miejsce.",
    "Built for heavy use, the 3-in-1 Boxer/Kicker/Hammer guarantees fun, competition, and excitement for players of all ages.": "Zaprojektowany do intensywnego użytkowania Boxer/Kicker/Hammer 3 w 1 gwarantuje zabawę, rywalizację i emocje graczom w każdym wieku.",
    "Bill acceptor.": "Akceptor banknotów.",
    "Nayax device.": "Urządzenie Nayax.",
    "Ticket dispenser.": "Dyspenser biletów.",
    "Custom sticker and branding (Advance orders).": "Indywidualne naklejki i oznakowanie marki (zamówienie z wyprzedzeniem).",
    "Silent mode (Advance orders).": "Tryb cichy (zamówienie z wyprzedzeniem).",
    "Height": "Wysokość",
    "Width": "Szerokość",
    "Length": "Długość",
    "Weight": "Waga",
    "Offers two exciting challenges in one compact machine with vibrant LED lights that bring extra attraction. Press the top Start button to release the punchball and test your strength or hit the bottom button to kick the football and show off your skills. Double the action, all in one game!": "Dwa ekscytujące wyzwania w jednym kompaktowym automacie, z intensywnym oświetleniem LED, które dodatkowo przyciąga uwagę. Naciśnij górny przycisk Start, aby zwolnić gruszkę bokserską i sprawdzić swoją siłę, lub dolny przycisk, aby kopnąć piłkę i pokazać swoje umiejętności. Podwójna akcja w jednej grze!",
    "Thrilling gameplay: Captivates players with exciting challenges that test their strength, ensuring they stay engaged and keep coming back for more fun.": "Ekscytująca rozgrywka: Wciąga graczy wyzwaniami sprawdzającymi ich siłę, utrzymuje zaangażowanie i zachęca do powrotu po kolejną porcję zabawy.",
    "Unmatched Durability & Convenience: Built with premium electronics and tough mechanics, making it perfect for high-traffic venues. Plus, it accepts bills, coins, cards, and tokens for seamless transactions.": "Niezrównana trwałość i wygoda: Wysokiej klasy elektronika i wytrzymała mechanika sprawiają, że urządzenie doskonale nadaje się do obiektów o dużym ruchu. Ponadto przyjmuje banknoty, monety, karty i żetony, zapewniając sprawne płatności.",
    "Boost Your Profits: Adjustable difficulty settings and free play modes to increase engagement and driving higher revenue.": "Zwiększ swoje zyski: Regulacja poziomu trudności i tryby gry bezpłatnej zwiększają zaangażowanie i przychody.",
    "This versatile machine offers three exciting challenges boxing, kicking and a prize feature all in one compact design. Equipped with vibrant LED lights for added attraction, players can showcase their strength and skill by hitting the punchball or football and get special prizes with extra motivation and excitement. It’s triple the action in one game!": "Ten wszechstronny automat oferuje trzy ekscytujące wyzwania: boksowanie, kopanie i funkcję nagród — wszystko w jednej kompaktowej konstrukcji. Intensywne oświetlenie LED dodatkowo przyciąga uwagę, a gracze mogą pokazać siłę i umiejętności, uderzając gruszkę bokserską lub kopiąc piłkę, oraz zdobywać specjalne nagrody, które zwiększają motywację i emocje. Potrójna akcja w jednej grze!",
    "This machine combines two exciting games in one: boxing and kicking! Perfectly designed for younger players, this machine brings twice the fun in a single unit, making it ideal for family-friendly venues.": "Ten automat łączy dwie ekscytujące gry w jednej: boksowanie i kopanie! Zaprojektowany specjalnie dla młodszych graczy, zapewnia podwójną zabawę w jednym urządzeniu i idealnie nadaje się do obiektów rodzinnych.",
    "2-in-1 Action: Combines boxing and kicking games for double the excitement.": "Akcja 2 w 1: Połączenie boksowania i kopania zapewnia podwójne emocje.",
    "Kid-Friendly Design: Tailored for children with a safe and easy-to-use layout.": "Konstrukcja przyjazna dzieciom: Dostosowany do dzieci, bezpieczny i łatwy w obsłudze układ.",
    "Bright LED Lights: Eye-catching lights make gameplay even more fun.": "Jasne oświetlenie LED: Przyciągające wzrok światła sprawiają, że gra jest jeszcze ciekawsza.",
    "Flexible Payment Options: Supports multiple payment types, including bills, coins, cards, and tokens, making it adaptable to any currency.": "Elastyczne opcje płatności: Obsługa banknotów, monet, kart i żetonów umożliwia dostosowanie do dowolnej waluty.",
    "Adjustable Play Mode: Set the game to different levels or free play mode to match the age and skill level of the players.": "Regulowany tryb gry: Ustaw różne poziomy lub tryb gry bezpłatnej, aby dopasować grę do wieku i umiejętności graczy.",
    "This machine combines three fun games in one: boxing, kicking and a prize feature! Designed for young players, it keeps kids engaged with exciting challenges and vibrant LED lights, making it a perfect fit for family venues.": "Ten automat łączy trzy zabawy w jednej: boksowanie, kopanie i funkcję nagród! Zaprojektowany dla młodych graczy, przyciąga dzieci ekscytującymi wyzwaniami i intensywnym oświetleniem LED, dzięki czemu doskonale pasuje do obiektów rodzinnych.",
    "3-in-1 Action: Offers boxing, kicking a prize reward option for extra excitement.": "Akcja 3 w 1: Boksowanie, kopanie i możliwość zdobywania nagród zapewniają dodatkowe emocje.",
    "Kid-Friendly Design: Safe, engaging and easy-to-use for children.": "Konstrukcja przyjazna dzieciom: Bezpieczna, angażująca i łatwa w obsłudze dla dzieci.",
    "Bright LED Lights: Colorful lights add to the fun and attraction.": "Jasne oświetlenie LED: Kolorowe światła zwiększają atrakcyjność i radość z gry.",
    "Immersive Experience: Captivating gameplay that challenges strength, keeping customers coming back for more.": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek.",
    "Built to Last: Designed with robust electronics and mechanics, perfect for high-traffic venues looking for reliable performance.": "Trwała konstrukcja: Solidna elektronika i mechanika, idealne dla obiektów o dużym ruchu, którym zależy na niezawodnym działaniu.",
    "Multible Payment Options: Supports a variety of payment methods, including bills, coins, cards, and tokens—suitable for any currency.": "Różne opcje płatności: Obsługuje banknoty, monety, karty i żetony — z możliwością dostosowania do dowolnej waluty.",
    "Revenue Booster: Adjustable difficulty levels and free play mode to engage diverse audiences and maximize profits.": "Zwiększanie przychodów: Regulowane poziomy trudności i tryb gry bezpłatnej angażują różne grupy odbiorców i maksymalizują zyski.",
    "Card reader.": "Czytnik kart.",
    "2 meter power cable.": "Przewód zasilający o długości 2 metrów.",
    "Protective cover.": "Pokrowiec ochronny.",
    "Custom sticker and branding.": "Indywidualne naklejki i oznakowanie marki.",
    "LED lighting variation available.": "Dostępny wariant oświetlenia LED.",
    "MULTIPLAYER BOXER MACHINE": "WIELOOSOBOWY AUTOMAT BOKSERSKI",
    "Boxer Fist is our new exciting multiplayer boxing arcade machine, built to entertain and challenge groups in any arcade, FEC, or entertainment venue. With its eye-catching LED lighting, modern decals, and robust construction, this machine invites competitive fun and repeat play.": "Boxer Fist to nasz nowy, ekscytujący wieloosobowy automat bokserski, stworzony, by bawić i stawiać wyzwania grupom w salonach gier, rodzinnych centrach rozrywki i innych obiektach rozrywkowych. Przyciągające wzrok oświetlenie LED, nowoczesne naklejki i solidna konstrukcja zachęcają do rywalizacji i kolejnych rozgrywek.",
    "Multiplayer Ready: Supports group challenges and head-to-head punching competitions. Perfect for friends, events, and team contests.": "Gotowy do gry wieloosobowej: Umożliwia wyzwania grupowe i bezpośrednią rywalizację w uderzeniach. Idealny dla przyjaciół, na wydarzenia i zawody drużynowe.",
    "Full LED Integration: Illuminated edges, buttons, and scoring panel to maximize visibility and energy.": "Pełna integracja LED: Podświetlane krawędzie, przyciski i panel wyników zapewniają maksymalną widoczność i energię.",
    "Heavy-Duty Frame: Reinforced body and impact-resistant build for long-term durability.": "Wytrzymała rama: Wzmocniona obudowa i konstrukcja odporna na uderzenia zapewniają długotrwałą wytrzymałość.",
    "Operator-Friendly: Reliable electronics, easy maintenance access, and cashless-ready setup.": "Przyjazny operatorowi: Niezawodna elektronika, łatwy dostęp serwisowy i przygotowanie do płatności bezgotówkowych.",
    "One of the latest additions to our lineup, Kids Combat offers an exciting, safe boxing experience for younger players. With its bold design and enhanced features, it’s ideal for arcades and family-friendly venues.": "Kids Combat, jeden z najnowszych modeli w naszej ofercie, zapewnia młodszym graczom ekscytującą i bezpieczną zabawę bokserską. Dzięki wyrazistemu wzornictwu i udoskonalonym funkcjom idealnie nadaje się do salonów gier i obiektów rodzinnych.",
    "Brand new Design: Fresh, engaging look tailored for kids.": "Zupełnie nowy design: Świeży, atrakcyjny wygląd dostosowany do dzieci.",
    "Safe and fun Gameplay: Perfect for younger players to safely enjoy the excitement of boxing.": "Bezpieczna i przyjemna rozgrywka: Idealna dla młodszych graczy, którzy chcą bezpiecznie cieszyć się emocjami boksowania.",
    "This machine is designed specifically for younger players, providing a fun and safe way to enjoy the excitement of a boxing game. With bright colors and engaging gameplay, it’s perfect for family-oriented locations.": "Ten automat został zaprojektowany specjalnie dla młodszych graczy i zapewnia bezpieczny oraz przyjemny sposób na poznanie emocji gry bokserskiej. Dzięki jaskrawym kolorom i angażującej rozgrywce doskonale sprawdza się w miejscach nastawionych na rodziny.",
    "Kid-Friendly Design: A smaller size and layout specifically made for children to enjoy.": "Konstrukcja przyjazna dzieciom: Mniejszy rozmiar i układ zaprojektowany specjalnie z myślą o zabawie dzieci.",
    "The Boxer Flash Gift offers an exciting twist by combining the classic boxing challenge with a rewarding gift feature. With bright LED lights and engaging gameplay.": "Boxer Flash Gift urozmaica klasyczne wyzwanie bokserskie funkcją zdobywania nagród. Oferuje jasne oświetlenie LED i angażującą rozgrywkę.",
    "Strength Challenge + Prizes: Players punch the bag, score high, and win special prizes.": "Wyzwanie siłowe i nagrody: Gracze uderzają w gruszkę, zdobywają wysokie wyniki i wygrywają specjalne nagrody.",
    "Flexible Payment Options: Supports a variety of payment methods, including bills, coins, cards, and tokens suitable for any currency.": "Elastyczne opcje płatności: Obsługuje banknoty, monety, karty i żetony, z możliwością dostosowania do dowolnej waluty.",
    "It is a classic strength-testing game that challenges players to hit as hard as they can. Perfect for amusement parks, arcades, and family entertainment centers (FECs), this timeless game is fun, competitive, and draws in crowds with its vibrant LED lights.": "To klasyczna gra mierząca siłę, w której gracze starają się uderzyć jak najmocniej. Idealna do parków rozrywki, salonów gier i rodzinnych centrów rozrywki (FEC), ta ponadczasowa gra zapewnia zabawę i rywalizację, a intensywne oświetlenie LED przyciąga tłumy.",
    "Power Strike Challenge: Swing the hammer and see how high you can score.": "Wyzwanie mocnego uderzenia: Zamachnij się młotem i sprawdź, jak wysoki wynik uzyskasz.",
    "Bright LED Lights: Eye-catching lights that enhance the excitement and attract attention.": "Jasne oświetlenie LED: Przyciągające wzrok światła zwiększają emocje i zwracają uwagę.",
    "Ticket Option: Can be set to reward tickets, making it ideal for redemption venues.": "Opcja biletowa: Możliwość przyznawania biletów jako nagrody sprawia, że urządzenie idealnie nadaje się do obiektów z grami redemption.",
    "Adjustable Difficulty & Free Play Mode: Suited for players of all ages and skill levels.": "Regulacja trudności i tryb gry bezpłatnej: Dla graczy w każdym wieku i na każdym poziomie umiejętności.",
    "This machine offers a thrilling and dynamic game designed for players who want to test their kicking strength and accuracy Perfect for both kids and adults, it’s a great addition to arcades, sports bars, and family entertainment centers.": "Ten automat oferuje ekscytującą, dynamiczną grę dla osób, które chcą sprawdzić siłę i celność kopnięcia. Idealny zarówno dla dzieci, jak i dorosłych, stanowi świetne uzupełnienie salonów gier, barów sportowych i rodzinnych centrów rozrywki.",
    "Kick Challenge: Players kick the ball to score points, testing their power and precision.": "Wyzwanie kopnięcia: Gracze kopią piłkę, aby zdobywać punkty, sprawdzając swoją siłę i precyzję.",
    "Adjustable Difficulty & Free Play Mode: Customizable for different ages and skill levels.": "Regulacja trudności i tryb gry bezpłatnej: Możliwość dostosowania do różnych grup wiekowych i poziomów umiejętności.",
    "The Boxer Gift offers an exciting twist by combining the classic boxing challenge with a rewarding gift feature. With bright LED lights and engaging gameplay.": "Boxer Gift urozmaica klasyczne wyzwanie bokserskie funkcją zdobywania nagród. Oferuje jasne oświetlenie LED i angażującą rozgrywkę.",
    "Small inflatable castles for children": "Małe dmuchane zamki dla dzieci",
    "The Mini XS inflatables are a fantastic attraction for the youngest guests at your event! These colourful inflatables instantly catch children’s attention and quickly become their favourite place to play.": "Dmuchane zamki Mini XS to fantastyczna atrakcja dla najmłodszych gości Twojego wydarzenia! Te kolorowe dmuchańce od razu przyciągają uwagę dzieci i szybko stają się ich ulubionym miejscem zabawy.",
    "Kids know they can enjoy unlimited fun inside. In the compact bouncy castle, they can jump, play, and burn off energy for hours. Some of our children’s inflatables also come with built-in slides.": "Dzieci wiedzą, że w środku czeka na nie nieograniczona zabawa. W kompaktowym dmuchanym zamku mogą godzinami skakać, bawić się i spożytkować energię. Niektóre z naszych dmuchańców dla dzieci mają również wbudowane zjeżdżalnie.",
    "Our small bouncy castles are always a big hit with children!": "Nasze małe dmuchane zamki zawsze cieszą się ogromnym powodzeniem wśród dzieci!",
    "The Golden air hockey is a new version of our bestseller indoor airhoockey.": "Cymbergaj Golden to nowa wersja naszego bestsellerowego modelu do wnętrz.",
    "Golden table boasts a refined and elegant design that blends seamlessly with any interior. Its subtle color palette, paired with tasteful golden accents, gives it a timeless appeal that never goes out of style. This table is not only a source of entertainment but also a sophisticated addition to any game room or leisure space.": "Stół Golden wyróżnia się dopracowanym, eleganckim wzornictwem, które harmonijnie pasuje do każdego wnętrza. Subtelna kolorystyka w połączeniu z gustownymi złotymi akcentami nadaje mu ponadczasowy wygląd, który nigdy nie wychodzi z mody. Ten stół to nie tylko źródło rozrywki, ale także stylowy dodatek do każdego pokoju gier lub przestrzeni wypoczynkowej.",
    "Solid construction proven by over 20 years of experience. Modern software allowing you to easily personalize different settings.": "Solidna konstrukcja sprawdzona przez ponad 20 lat doświadczenia. Nowoczesne oprogramowanie umożliwia łatwą personalizację różnych ustawień.",
    "Please note:": "Uwaga:",
    "The lamp shown is an optional accessory - it is not sold as standard equipment.": "Przedstawiona lampa jest wyposażeniem opcjonalnym — nie jest sprzedawana w standardzie.",
    "stainless perforated metal playfield": "Perforowane pole gry z metalu nierdzewnego",
    "system of lighting LED in playfield": "System oświetlenia LED w polu gry",
    "system of lighting LED in legs": "System oświetlenia LED w nogach",
    "digital score display in standard/LED lamp optional": "Cyfrowy wyświetlacz wyników w standardzie / lampa LED opcjonalnie",
    "polycarbonate barrier in the middle of playfield": "Poliwęglanowa przegroda na środku pola gry",
    "air pump 260 W": "Pompa powietrza 260 W",
    "power supply 230v/50Hz": "Zasilanie 230 V / 50 Hz",
    "power consumption 82 W (demo mode), 260 W (game mode)": "Pobór mocy 82 W (tryb demonstracyjny), 260 W (tryb gry)",
    "accessories included: 4 mallets, 6 pucks, 100 tokens (if programmed for tokens)": "Akcesoria w zestawie: 4 odbijaki, 6 krążków, 100 żetonów (jeśli zaprogramowano na żetony)",
    "Warranty: 12 months for enterprises, 24 months for consumers": "Gwarancja: 12 miesięcy dla przedsiębiorców, 24 miesiące dla konsumentów",
    "optional - ticket dispenser, bill acceptor, card reader": "Opcjonalnie — dyspenser biletów, akceptor banknotów, czytnik kart",
    "Product: LxWxH // Weight": "Produkt: dł. × szer. × wys. // waga",
    "Package: LxWxH // Weight": "Opakowanie: dł. × szer. × wys. // waga",
    "AIR HOCKEY ARCTIC is a 100% waterproof device that can be used outdoors all year round, just like indoors. It is one of the most popular machines. Solid construction proven by over 20 years of experience. Modern software allows you to easily personalize different settings.": "AIR HOCKEY ARCTIC to w 100% wodoodporne urządzenie, które może być używane przez cały rok na zewnątrz, tak samo jak wewnątrz. To jeden z najpopularniejszych automatów. Solidna konstrukcja sprawdzona przez ponad 20 lat doświadczenia. Nowoczesne oprogramowanie pozwala łatwo personalizować różne ustawienia.",
    "COMESTERO RM5 or NRI electronic coin acceptor": "Elektroniczny wrzutnik monet COMESTERO RM5 lub NRI",
    "polycarbonate perforated playfield": "Perforowane pole gry z poliwęglanu",
    "polycarbonate top frame around the playfield with a lighting system": "Górna rama z poliwęglanu wokół pola gry z systemem oświetlenia",
    "polycarbonate barrier on both sides and in the center of a playfield": "Poliwęglanowa przegroda po obu stronach i na środku pola gry",
    "LED lightning system in the playfield": "System oświetlenia LED w polu gry",
    "LED lightning system in the legs": "System oświetlenia LED w nogach",
    "digital score display for each player": "Cyfrowy wyświetlacz wyniku dla każdego gracza",
    "standard power supply 230v/50Hz": "Standardowe zasilanie 230 V / 50 Hz",
    "power consumption 60 W (demo mode), 390 W (game mode)": "Pobór mocy 60 W (tryb demonstracyjny), 390 W (tryb gry)",
    "accessories included: 4 mallets, 6 pucks, 100 tokens (if token-programmed)": "Akcesoria w zestawie: 4 odbijaki, 6 krążków, 100 żetonów (jeśli zaprogramowano na żetony)",
    "warranty: 12 months for enterprises, 24 months for consumers": "Gwarancja: 12 miesięcy dla przedsiębiorców, 24 miesiące dla konsumentów",
    "Check out our brand new airhockey Matrix! LED display isn't only there to look amazing - it also communicates game updates and events, showing 'SCORE!' when a goal is scored, and a commiserating 'OH NO!' when you concede a goal. Countdown timers at each end keep you informed of time left to play, and the whole display flexes, colour-shifts and pulsates in perfect sync with your game. Customisable operator settings allow you to configure the table exactly as you want it and the 260w air pump creates a cushion of air across the playfield for the fastest speeds.": "Poznaj nasz zupełnie nowy cymbergaj Matrix! Wyświetlacz LED nie tylko świetnie wygląda — przekazuje też informacje o przebiegu gry, pokazując „SCORE!” po zdobyciu gola i współczujące „OH NO!”, gdy stracisz bramkę. Liczniki na obu końcach informują o pozostałym czasie, a cały wyświetlacz zmienia wygląd, kolory i pulsuje w idealnej synchronizacji z grą. Konfigurowalne ustawienia operatora pozwalają dopasować stół do własnych potrzeb, a pompa powietrza o mocy 260 W tworzy poduszkę powietrzną nad polem gry, zapewniając największe prędkości.",
    "Air hockey has been around for a long time, with only rarely a major paradigm shift in design or functionality. Now the Matrix knocks the sector out of the park with its integrated LED displays and systems. If you're looking for a truly spectacular centrepiece for your venue - or even for your private games room - then take the red pill and enter the Matrix now!": "Cymbergaj istnieje od dawna, a duże przełomy we wzornictwie lub funkcjonalności zdarzają się rzadko. Teraz Matrix wyznacza nowy poziom dzięki zintegrowanym wyświetlaczom i systemom LED. Jeśli szukasz naprawdę spektakularnej głównej atrakcji do swojego lokalu — lub nawet prywatnego pokoju gier — wybierz czerwoną pigułkę i wejdź do Matrixa już teraz!",
    "Futuristic commercial air hockey table.": "Futurystyczny komercyjny stół do cymbergaja.",
    "Suitable for amusement arcades, commercial venues & homes.": "Do salonów gier, obiektów komercyjnych i domów.",
    "Unique LED matrix light display incorporating game commentary.": "Wyjątkowy matrycowy wyświetlacz LED z komentarzami do gry.",
    "LED score displays and message updates.": "Wyświetlacze LED z wynikami i komunikatami.",
    "Sound system with in-game audio.": "System dźwiękowy z efektami podczas gry.",
    "Electronic coin acceptor included - freeplay game as an option.": "Elektroniczny wrzutnik monet w zestawie — opcjonalny tryb gry bezpłatnej.",
    "Includes four pushers and six pucks.": "W zestawie cztery odbijaki i sześć krążków.",
    "New basketball machine from WIK, compact size allows pass through 80cm wide doorways. Customized height 248-310cm.": "Nowy automat do koszykówki firmy WIK. Kompaktowe wymiary umożliwiają przejazd przez drzwi o szerokości 80 cm. Wysokość dostosowywana w zakresie 248–310 cm.",
    "electronic coin acceptor COMESTERO RM5": "Elektroniczny wrzutnik monet COMESTERO RM5",
    "construction made of metal and laminated polycarbonate": "Konstrukcja z metalu i laminowanego poliwęglanu",
    "digital score, credit and record display": "Cyfrowy wyświetlacz wyniku, kredytów i rekordu",
    "linking option": "Opcja łączenia urządzeń",
    "moving basket": "Ruchomy kosz",
    "5 balls included": "5 piłek w zestawie",
    "easy moving system (6 wheels with blockade system)": "System łatwego przemieszczania (6 kół z blokadą)",
    "easy and fast assembly": "Łatwy i szybki montaż",
    "power supply 230V/50Hz": "Zasilanie 230 V / 50 Hz",
    "power consumption: 105 W (demo mode), 180 W (game mode)": "Pobór mocy: 105 W (tryb demonstracyjny), 180 W (tryb gry)",
    "warranty: 12 months": "Gwarancja: 12 miesięcy",
    "optional: ticket dispenser, bill acceptor, card reader": "Opcjonalnie: dyspenser biletów, akceptor banknotów, czytnik kart",
    "Our weatherproof basketball arcade machines can be used outdoor all year round. The game has four levels of difficulty and comes with a set of five balls. Depending on the mode selected, the basket can be movable.": "Nasze odporne na warunki atmosferyczne automaty do koszykówki mogą być używane na zewnątrz przez cały rok. Gra ma cztery poziomy trudności i jest dostarczana z zestawem pięciu piłek. W zależności od wybranego trybu kosz może się poruszać.",
    "It is very easy to assemble and transport.": "Montaż i transport są bardzo łatwe.",
    "Basketball is a game for all ages with both kids and adults loving this game. Players can play in a group and compete for the best score (linking option). It's a high quality long lasting machine. WIK is a leader in making the basketball arcade machines with years of experience. This is a crowd pleaser that never ceases to provide fun.": "Koszykówka to gra dla osób w każdym wieku, uwielbiana zarówno przez dzieci, jak i dorosłych. Gracze mogą grać w grupie i rywalizować o najlepszy wynik (opcja łączenia urządzeń). To wysokiej jakości, trwały automat. WIK jest liderem produkcji automatów do koszykówki z wieloletnim doświadczeniem. To atrakcja lubiana przez publiczność, która nie przestaje dostarczać zabawy.",
    "east and fast assembly": "Łatwy i szybki montaż",
    "power conumption: 105 W (demo mode), 180 W (game mode)": "Pobór mocy: 105 W (tryb demonstracyjny), 180 W (tryb gry)",
    "Dimensions": "Wymiary",
    "Power supply": "Zasilanie",
    "Power consumption": "Pobór mocy",
    "To be confirmed": "Do potwierdzenia"
  },
  "features": {
    "3-in-1 Amusement Machine: Boxer, Kicker & Hammer": "Automat rozrywkowy 3 w 1: Boxer, Kicker i Hammer",
    "This innovative 3-in-1 arcade machine combines three popular strength-testing games in one compact unit — Boxer, Kicker, and Hammer.": "Ten innowacyjny automat 3 w 1 łączy trzy popularne gry mierzące siłę w jednym kompaktowym urządzeniu — Boxer, Kicker i Hammer.",
    "Players can test their power by choosing between punching, kicking, or hammering modes, all integrated into a single durable and eye-catching cabinet.": "Gracze mogą sprawdzić swoją siłę, wybierając uderzanie pięścią, kopanie lub uderzanie młotem — wszystko w jednej trwałej i przyciągającej wzrok obudowie.",
    "The machine features a modern design with LED lighting, high-quality sensors for accurate scoring": "Automat wyróżnia się nowoczesnym wzornictwem z oświetleniem LED oraz wysokiej jakości czujnikami zapewniającymi dokładny pomiar wyniku",
    "Perfect for bars, amusement centers, and events, it offers maximum entertainment value while saving space.": "Idealny do barów, centrów rozrywki i na wydarzenia — zapewnia maksimum rozrywki, jednocześnie oszczędzając miejsce.",
    "Built for heavy use, the 3-in-1 Boxer/Kicker/Hammer guarantees fun, competition, and excitement for players of all ages.": "Zaprojektowany do intensywnego użytkowania Boxer/Kicker/Hammer 3 w 1 gwarantuje zabawę, rywalizację i emocje graczom w każdym wieku.",
    "Bill acceptor.": "Akceptor banknotów.",
    "Nayax device.": "Urządzenie Nayax.",
    "Ticket dispenser.": "Dyspenser biletów.",
    "Custom sticker and branding (Advance orders).": "Indywidualne naklejki i oznakowanie marki (zamówienie z wyprzedzeniem).",
    "Silent mode (Advance orders).": "Tryb cichy (zamówienie z wyprzedzeniem).",
    "Height": "Wysokość",
    "Width": "Szerokość",
    "Length": "Długość",
    "Weight": "Waga",
    "Offers two exciting challenges in one compact machine with vibrant LED lights that bring extra attraction. Press the top Start button to release the punchball and test your strength or hit the bottom button to kick the football and show off your skills. Double the action, all in one game!": "Dwa ekscytujące wyzwania w jednym kompaktowym automacie, z intensywnym oświetleniem LED, które dodatkowo przyciąga uwagę. Naciśnij górny przycisk Start, aby zwolnić gruszkę bokserską i sprawdzić swoją siłę, lub dolny przycisk, aby kopnąć piłkę i pokazać swoje umiejętności. Podwójna akcja w jednej grze!",
    "Thrilling gameplay: Captivates players with exciting challenges that test their strength, ensuring they stay engaged and keep coming back for more fun.": "Ekscytująca rozgrywka: Wciąga graczy wyzwaniami sprawdzającymi ich siłę, utrzymuje zaangażowanie i zachęca do powrotu po kolejną porcję zabawy.",
    "Unmatched Durability & Convenience: Built with premium electronics and tough mechanics, making it perfect for high-traffic venues. Plus, it accepts bills, coins, cards, and tokens for seamless transactions.": "Niezrównana trwałość i wygoda: Wysokiej klasy elektronika i wytrzymała mechanika sprawiają, że urządzenie doskonale nadaje się do obiektów o dużym ruchu. Ponadto przyjmuje banknoty, monety, karty i żetony, zapewniając sprawne płatności.",
    "Boost Your Profits: Adjustable difficulty settings and free play modes to increase engagement and driving higher revenue.": "Zwiększ swoje zyski: Regulacja poziomu trudności i tryby gry bezpłatnej zwiększają zaangażowanie i przychody.",
    "This versatile machine offers three exciting challenges boxing, kicking and a prize feature all in one compact design. Equipped with vibrant LED lights for added attraction, players can showcase their strength and skill by hitting the punchball or football and get special prizes with extra motivation and excitement. It’s triple the action in one game!": "Ten wszechstronny automat oferuje trzy ekscytujące wyzwania: boksowanie, kopanie i funkcję nagród — wszystko w jednej kompaktowej konstrukcji. Intensywne oświetlenie LED dodatkowo przyciąga uwagę, a gracze mogą pokazać siłę i umiejętności, uderzając gruszkę bokserską lub kopiąc piłkę, oraz zdobywać specjalne nagrody, które zwiększają motywację i emocje. Potrójna akcja w jednej grze!",
    "This machine combines two exciting games in one: boxing and kicking! Perfectly designed for younger players, this machine brings twice the fun in a single unit, making it ideal for family-friendly venues.": "Ten automat łączy dwie ekscytujące gry w jednej: boksowanie i kopanie! Zaprojektowany specjalnie dla młodszych graczy, zapewnia podwójną zabawę w jednym urządzeniu i idealnie nadaje się do obiektów rodzinnych.",
    "2-in-1 Action: Combines boxing and kicking games for double the excitement.": "Akcja 2 w 1: Połączenie boksowania i kopania zapewnia podwójne emocje.",
    "Kid-Friendly Design: Tailored for children with a safe and easy-to-use layout.": "Konstrukcja przyjazna dzieciom: Dostosowany do dzieci, bezpieczny i łatwy w obsłudze układ.",
    "Bright LED Lights: Eye-catching lights make gameplay even more fun.": "Jasne oświetlenie LED: Przyciągające wzrok światła sprawiają, że gra jest jeszcze ciekawsza.",
    "Flexible Payment Options: Supports multiple payment types, including bills, coins, cards, and tokens, making it adaptable to any currency.": "Elastyczne opcje płatności: Obsługa banknotów, monet, kart i żetonów umożliwia dostosowanie do dowolnej waluty.",
    "Adjustable Play Mode: Set the game to different levels or free play mode to match the age and skill level of the players.": "Regulowany tryb gry: Ustaw różne poziomy lub tryb gry bezpłatnej, aby dopasować grę do wieku i umiejętności graczy.",
    "This machine combines three fun games in one: boxing, kicking and a prize feature! Designed for young players, it keeps kids engaged with exciting challenges and vibrant LED lights, making it a perfect fit for family venues.": "Ten automat łączy trzy zabawy w jednej: boksowanie, kopanie i funkcję nagród! Zaprojektowany dla młodych graczy, przyciąga dzieci ekscytującymi wyzwaniami i intensywnym oświetleniem LED, dzięki czemu doskonale pasuje do obiektów rodzinnych.",
    "3-in-1 Action: Offers boxing, kicking a prize reward option for extra excitement.": "Akcja 3 w 1: Boksowanie, kopanie i możliwość zdobywania nagród zapewniają dodatkowe emocje.",
    "Kid-Friendly Design: Safe, engaging and easy-to-use for children.": "Konstrukcja przyjazna dzieciom: Bezpieczna, angażująca i łatwa w obsłudze dla dzieci.",
    "Bright LED Lights: Colorful lights add to the fun and attraction.": "Jasne oświetlenie LED: Kolorowe światła zwiększają atrakcyjność i radość z gry.",
    "Immersive Experience: Captivating gameplay that challenges strength, keeping customers coming back for more.": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek.",
    "Built to Last: Designed with robust electronics and mechanics, perfect for high-traffic venues looking for reliable performance.": "Trwała konstrukcja: Solidna elektronika i mechanika, idealne dla obiektów o dużym ruchu, którym zależy na niezawodnym działaniu.",
    "Multible Payment Options: Supports a variety of payment methods, including bills, coins, cards, and tokens—suitable for any currency.": "Różne opcje płatności: Obsługuje banknoty, monety, karty i żetony — z możliwością dostosowania do dowolnej waluty.",
    "Revenue Booster: Adjustable difficulty levels and free play mode to engage diverse audiences and maximize profits.": "Zwiększanie przychodów: Regulowane poziomy trudności i tryb gry bezpłatnej angażują różne grupy odbiorców i maksymalizują zyski.",
    "Card reader.": "Czytnik kart.",
    "2 meter power cable.": "Przewód zasilający o długości 2 metrów.",
    "Protective cover.": "Pokrowiec ochronny.",
    "Custom sticker and branding.": "Indywidualne naklejki i oznakowanie marki.",
    "LED lighting variation available.": "Dostępny wariant oświetlenia LED.",
    "MULTIPLAYER BOXER MACHINE": "WIELOOSOBOWY AUTOMAT BOKSERSKI",
    "Boxer Fist is our new exciting multiplayer boxing arcade machine, built to entertain and challenge groups in any arcade, FEC, or entertainment venue. With its eye-catching LED lighting, modern decals, and robust construction, this machine invites competitive fun and repeat play.": "Boxer Fist to nasz nowy, ekscytujący wieloosobowy automat bokserski, stworzony, by bawić i stawiać wyzwania grupom w salonach gier, rodzinnych centrach rozrywki i innych obiektach rozrywkowych. Przyciągające wzrok oświetlenie LED, nowoczesne naklejki i solidna konstrukcja zachęcają do rywalizacji i kolejnych rozgrywek.",
    "Multiplayer Ready: Supports group challenges and head-to-head punching competitions. Perfect for friends, events, and team contests.": "Gotowy do gry wieloosobowej: Umożliwia wyzwania grupowe i bezpośrednią rywalizację w uderzeniach. Idealny dla przyjaciół, na wydarzenia i zawody drużynowe.",
    "Full LED Integration: Illuminated edges, buttons, and scoring panel to maximize visibility and energy.": "Pełna integracja LED: Podświetlane krawędzie, przyciski i panel wyników zapewniają maksymalną widoczność i energię.",
    "Heavy-Duty Frame: Reinforced body and impact-resistant build for long-term durability.": "Wytrzymała rama: Wzmocniona obudowa i konstrukcja odporna na uderzenia zapewniają długotrwałą wytrzymałość.",
    "Operator-Friendly: Reliable electronics, easy maintenance access, and cashless-ready setup.": "Przyjazny operatorowi: Niezawodna elektronika, łatwy dostęp serwisowy i przygotowanie do płatności bezgotówkowych.",
    "One of the latest additions to our lineup, Kids Combat offers an exciting, safe boxing experience for younger players. With its bold design and enhanced features, it’s ideal for arcades and family-friendly venues.": "Kids Combat, jeden z najnowszych modeli w naszej ofercie, zapewnia młodszym graczom ekscytującą i bezpieczną zabawę bokserską. Dzięki wyrazistemu wzornictwu i udoskonalonym funkcjom idealnie nadaje się do salonów gier i obiektów rodzinnych.",
    "Brand new Design: Fresh, engaging look tailored for kids.": "Zupełnie nowy design: Świeży, atrakcyjny wygląd dostosowany do dzieci.",
    "Safe and fun Gameplay: Perfect for younger players to safely enjoy the excitement of boxing.": "Bezpieczna i przyjemna rozgrywka: Idealna dla młodszych graczy, którzy chcą bezpiecznie cieszyć się emocjami boksowania.",
    "This machine is designed specifically for younger players, providing a fun and safe way to enjoy the excitement of a boxing game. With bright colors and engaging gameplay, it’s perfect for family-oriented locations.": "Ten automat został zaprojektowany specjalnie dla młodszych graczy i zapewnia bezpieczny oraz przyjemny sposób na poznanie emocji gry bokserskiej. Dzięki jaskrawym kolorom i angażującej rozgrywce doskonale sprawdza się w miejscach nastawionych na rodziny.",
    "Kid-Friendly Design: A smaller size and layout specifically made for children to enjoy.": "Konstrukcja przyjazna dzieciom: Mniejszy rozmiar i układ zaprojektowany specjalnie z myślą o zabawie dzieci.",
    "The Boxer Flash Gift offers an exciting twist by combining the classic boxing challenge with a rewarding gift feature. With bright LED lights and engaging gameplay.": "Boxer Flash Gift urozmaica klasyczne wyzwanie bokserskie funkcją zdobywania nagród. Oferuje jasne oświetlenie LED i angażującą rozgrywkę.",
    "Strength Challenge + Prizes: Players punch the bag, score high, and win special prizes.": "Wyzwanie siłowe i nagrody: Gracze uderzają w gruszkę, zdobywają wysokie wyniki i wygrywają specjalne nagrody.",
    "Flexible Payment Options: Supports a variety of payment methods, including bills, coins, cards, and tokens suitable for any currency.": "Elastyczne opcje płatności: Obsługuje banknoty, monety, karty i żetony, z możliwością dostosowania do dowolnej waluty.",
    "It is a classic strength-testing game that challenges players to hit as hard as they can. Perfect for amusement parks, arcades, and family entertainment centers (FECs), this timeless game is fun, competitive, and draws in crowds with its vibrant LED lights.": "To klasyczna gra mierząca siłę, w której gracze starają się uderzyć jak najmocniej. Idealna do parków rozrywki, salonów gier i rodzinnych centrów rozrywki (FEC), ta ponadczasowa gra zapewnia zabawę i rywalizację, a intensywne oświetlenie LED przyciąga tłumy.",
    "Power Strike Challenge: Swing the hammer and see how high you can score.": "Wyzwanie mocnego uderzenia: Zamachnij się młotem i sprawdź, jak wysoki wynik uzyskasz.",
    "Bright LED Lights: Eye-catching lights that enhance the excitement and attract attention.": "Jasne oświetlenie LED: Przyciągające wzrok światła zwiększają emocje i zwracają uwagę.",
    "Ticket Option: Can be set to reward tickets, making it ideal for redemption venues.": "Opcja biletowa: Możliwość przyznawania biletów jako nagrody sprawia, że urządzenie idealnie nadaje się do obiektów z grami redemption.",
    "Adjustable Difficulty & Free Play Mode: Suited for players of all ages and skill levels.": "Regulacja trudności i tryb gry bezpłatnej: Dla graczy w każdym wieku i na każdym poziomie umiejętności.",
    "This machine offers a thrilling and dynamic game designed for players who want to test their kicking strength and accuracy Perfect for both kids and adults, it’s a great addition to arcades, sports bars, and family entertainment centers.": "Ten automat oferuje ekscytującą, dynamiczną grę dla osób, które chcą sprawdzić siłę i celność kopnięcia. Idealny zarówno dla dzieci, jak i dorosłych, stanowi świetne uzupełnienie salonów gier, barów sportowych i rodzinnych centrów rozrywki.",
    "Kick Challenge: Players kick the ball to score points, testing their power and precision.": "Wyzwanie kopnięcia: Gracze kopią piłkę, aby zdobywać punkty, sprawdzając swoją siłę i precyzję.",
    "Adjustable Difficulty & Free Play Mode: Customizable for different ages and skill levels.": "Regulacja trudności i tryb gry bezpłatnej: Możliwość dostosowania do różnych grup wiekowych i poziomów umiejętności.",
    "The Boxer Gift offers an exciting twist by combining the classic boxing challenge with a rewarding gift feature. With bright LED lights and engaging gameplay.": "Boxer Gift urozmaica klasyczne wyzwanie bokserskie funkcją zdobywania nagród. Oferuje jasne oświetlenie LED i angażującą rozgrywkę.",
    "Small inflatable castles for children": "Małe dmuchane zamki dla dzieci",
    "The Mini XS inflatables are a fantastic attraction for the youngest guests at your event! These colourful inflatables instantly catch children’s attention and quickly become their favourite place to play.": "Dmuchane zamki Mini XS to fantastyczna atrakcja dla najmłodszych gości Twojego wydarzenia! Te kolorowe dmuchańce od razu przyciągają uwagę dzieci i szybko stają się ich ulubionym miejscem zabawy.",
    "Kids know they can enjoy unlimited fun inside. In the compact bouncy castle, they can jump, play, and burn off energy for hours. Some of our children’s inflatables also come with built-in slides.": "Dzieci wiedzą, że w środku czeka na nie nieograniczona zabawa. W kompaktowym dmuchanym zamku mogą godzinami skakać, bawić się i spożytkować energię. Niektóre z naszych dmuchańców dla dzieci mają również wbudowane zjeżdżalnie.",
    "Our small bouncy castles are always a big hit with children!": "Nasze małe dmuchane zamki zawsze cieszą się ogromnym powodzeniem wśród dzieci!",
    "The Golden air hockey is a new version of our bestseller indoor airhoockey.": "Cymbergaj Golden to nowa wersja naszego bestsellerowego modelu do wnętrz.",
    "Golden table boasts a refined and elegant design that blends seamlessly with any interior. Its subtle color palette, paired with tasteful golden accents, gives it a timeless appeal that never goes out of style. This table is not only a source of entertainment but also a sophisticated addition to any game room or leisure space.": "Stół Golden wyróżnia się dopracowanym, eleganckim wzornictwem, które harmonijnie pasuje do każdego wnętrza. Subtelna kolorystyka w połączeniu z gustownymi złotymi akcentami nadaje mu ponadczasowy wygląd, który nigdy nie wychodzi z mody. Ten stół to nie tylko źródło rozrywki, ale także stylowy dodatek do każdego pokoju gier lub przestrzeni wypoczynkowej.",
    "Solid construction proven by over 20 years of experience. Modern software allowing you to easily personalize different settings.": "Solidna konstrukcja sprawdzona przez ponad 20 lat doświadczenia. Nowoczesne oprogramowanie umożliwia łatwą personalizację różnych ustawień.",
    "Please note:": "Uwaga:",
    "The lamp shown is an optional accessory - it is not sold as standard equipment.": "Przedstawiona lampa jest wyposażeniem opcjonalnym — nie jest sprzedawana w standardzie.",
    "stainless perforated metal playfield": "Perforowane pole gry z metalu nierdzewnego",
    "system of lighting LED in playfield": "System oświetlenia LED w polu gry",
    "system of lighting LED in legs": "System oświetlenia LED w nogach",
    "digital score display in standard/LED lamp optional": "Cyfrowy wyświetlacz wyników w standardzie / lampa LED opcjonalnie",
    "polycarbonate barrier in the middle of playfield": "Poliwęglanowa przegroda na środku pola gry",
    "air pump 260 W": "Pompa powietrza 260 W",
    "power supply 230v/50Hz": "Zasilanie 230 V / 50 Hz",
    "power consumption 82 W (demo mode), 260 W (game mode)": "Pobór mocy 82 W (tryb demonstracyjny), 260 W (tryb gry)",
    "accessories included: 4 mallets, 6 pucks, 100 tokens (if programmed for tokens)": "Akcesoria w zestawie: 4 odbijaki, 6 krążków, 100 żetonów (jeśli zaprogramowano na żetony)",
    "Warranty: 12 months for enterprises, 24 months for consumers": "Gwarancja: 12 miesięcy dla przedsiębiorców, 24 miesiące dla konsumentów",
    "optional - ticket dispenser, bill acceptor, card reader": "Opcjonalnie — dyspenser biletów, akceptor banknotów, czytnik kart",
    "Product: LxWxH // Weight": "Produkt: dł. × szer. × wys. // waga",
    "Package: LxWxH // Weight": "Opakowanie: dł. × szer. × wys. // waga",
    "AIR HOCKEY ARCTIC is a 100% waterproof device that can be used outdoors all year round, just like indoors. It is one of the most popular machines. Solid construction proven by over 20 years of experience. Modern software allows you to easily personalize different settings.": "AIR HOCKEY ARCTIC to w 100% wodoodporne urządzenie, które może być używane przez cały rok na zewnątrz, tak samo jak wewnątrz. To jeden z najpopularniejszych automatów. Solidna konstrukcja sprawdzona przez ponad 20 lat doświadczenia. Nowoczesne oprogramowanie pozwala łatwo personalizować różne ustawienia.",
    "COMESTERO RM5 or NRI electronic coin acceptor": "Elektroniczny wrzutnik monet COMESTERO RM5 lub NRI",
    "polycarbonate perforated playfield": "Perforowane pole gry z poliwęglanu",
    "polycarbonate top frame around the playfield with a lighting system": "Górna rama z poliwęglanu wokół pola gry z systemem oświetlenia",
    "polycarbonate barrier on both sides and in the center of a playfield": "Poliwęglanowa przegroda po obu stronach i na środku pola gry",
    "LED lightning system in the playfield": "System oświetlenia LED w polu gry",
    "LED lightning system in the legs": "System oświetlenia LED w nogach",
    "digital score display for each player": "Cyfrowy wyświetlacz wyniku dla każdego gracza",
    "standard power supply 230v/50Hz": "Standardowe zasilanie 230 V / 50 Hz",
    "power consumption 60 W (demo mode), 390 W (game mode)": "Pobór mocy 60 W (tryb demonstracyjny), 390 W (tryb gry)",
    "accessories included: 4 mallets, 6 pucks, 100 tokens (if token-programmed)": "Akcesoria w zestawie: 4 odbijaki, 6 krążków, 100 żetonów (jeśli zaprogramowano na żetony)",
    "warranty: 12 months for enterprises, 24 months for consumers": "Gwarancja: 12 miesięcy dla przedsiębiorców, 24 miesiące dla konsumentów",
    "Check out our brand new airhockey Matrix! LED display isn't only there to look amazing - it also communicates game updates and events, showing 'SCORE!' when a goal is scored, and a commiserating 'OH NO!' when you concede a goal. Countdown timers at each end keep you informed of time left to play, and the whole display flexes, colour-shifts and pulsates in perfect sync with your game. Customisable operator settings allow you to configure the table exactly as you want it and the 260w air pump creates a cushion of air across the playfield for the fastest speeds.": "Poznaj nasz zupełnie nowy cymbergaj Matrix! Wyświetlacz LED nie tylko świetnie wygląda — przekazuje też informacje o przebiegu gry, pokazując „SCORE!” po zdobyciu gola i współczujące „OH NO!”, gdy stracisz bramkę. Liczniki na obu końcach informują o pozostałym czasie, a cały wyświetlacz zmienia wygląd, kolory i pulsuje w idealnej synchronizacji z grą. Konfigurowalne ustawienia operatora pozwalają dopasować stół do własnych potrzeb, a pompa powietrza o mocy 260 W tworzy poduszkę powietrzną nad polem gry, zapewniając największe prędkości.",
    "Air hockey has been around for a long time, with only rarely a major paradigm shift in design or functionality. Now the Matrix knocks the sector out of the park with its integrated LED displays and systems. If you're looking for a truly spectacular centrepiece for your venue - or even for your private games room - then take the red pill and enter the Matrix now!": "Cymbergaj istnieje od dawna, a duże przełomy we wzornictwie lub funkcjonalności zdarzają się rzadko. Teraz Matrix wyznacza nowy poziom dzięki zintegrowanym wyświetlaczom i systemom LED. Jeśli szukasz naprawdę spektakularnej głównej atrakcji do swojego lokalu — lub nawet prywatnego pokoju gier — wybierz czerwoną pigułkę i wejdź do Matrixa już teraz!",
    "Futuristic commercial air hockey table.": "Futurystyczny komercyjny stół do cymbergaja.",
    "Suitable for amusement arcades, commercial venues & homes.": "Do salonów gier, obiektów komercyjnych i domów.",
    "Unique LED matrix light display incorporating game commentary.": "Wyjątkowy matrycowy wyświetlacz LED z komentarzami do gry.",
    "LED score displays and message updates.": "Wyświetlacze LED z wynikami i komunikatami.",
    "Sound system with in-game audio.": "System dźwiękowy z efektami podczas gry.",
    "Electronic coin acceptor included - freeplay game as an option.": "Elektroniczny wrzutnik monet w zestawie — opcjonalny tryb gry bezpłatnej.",
    "Includes four pushers and six pucks.": "W zestawie cztery odbijaki i sześć krążków.",
    "New basketball machine from WIK, compact size allows pass through 80cm wide doorways. Customized height 248-310cm.": "Nowy automat do koszykówki firmy WIK. Kompaktowe wymiary umożliwiają przejazd przez drzwi o szerokości 80 cm. Wysokość dostosowywana w zakresie 248–310 cm.",
    "electronic coin acceptor COMESTERO RM5": "Elektroniczny wrzutnik monet COMESTERO RM5",
    "construction made of metal and laminated polycarbonate": "Konstrukcja z metalu i laminowanego poliwęglanu",
    "digital score, credit and record display": "Cyfrowy wyświetlacz wyniku, kredytów i rekordu",
    "linking option": "Opcja łączenia urządzeń",
    "moving basket": "Ruchomy kosz",
    "5 balls included": "5 piłek w zestawie",
    "easy moving system (6 wheels with blockade system)": "System łatwego przemieszczania (6 kół z blokadą)",
    "easy and fast assembly": "Łatwy i szybki montaż",
    "power supply 230V/50Hz": "Zasilanie 230 V / 50 Hz",
    "power consumption: 105 W (demo mode), 180 W (game mode)": "Pobór mocy: 105 W (tryb demonstracyjny), 180 W (tryb gry)",
    "warranty: 12 months": "Gwarancja: 12 miesięcy",
    "optional: ticket dispenser, bill acceptor, card reader": "Opcjonalnie: dyspenser biletów, akceptor banknotów, czytnik kart",
    "Our weatherproof basketball arcade machines can be used outdoor all year round. The game has four levels of difficulty and comes with a set of five balls. Depending on the mode selected, the basket can be movable.": "Nasze odporne na warunki atmosferyczne automaty do koszykówki mogą być używane na zewnątrz przez cały rok. Gra ma cztery poziomy trudności i jest dostarczana z zestawem pięciu piłek. W zależności od wybranego trybu kosz może się poruszać.",
    "It is very easy to assemble and transport.": "Montaż i transport są bardzo łatwe.",
    "Basketball is a game for all ages with both kids and adults loving this game. Players can play in a group and compete for the best score (linking option). It's a high quality long lasting machine. WIK is a leader in making the basketball arcade machines with years of experience. This is a crowd pleaser that never ceases to provide fun.": "Koszykówka to gra dla osób w każdym wieku, uwielbiana zarówno przez dzieci, jak i dorosłych. Gracze mogą grać w grupie i rywalizować o najlepszy wynik (opcja łączenia urządzeń). To wysokiej jakości, trwały automat. WIK jest liderem produkcji automatów do koszykówki z wieloletnim doświadczeniem. To atrakcja lubiana przez publiczność, która nie przestaje dostarczać zabawy.",
    "east and fast assembly": "Łatwy i szybki montaż",
    "power conumption: 105 W (demo mode), 180 W (game mode)": "Pobór mocy: 105 W (tryb demonstracyjny), 180 W (tryb gry)"
  },
  "options": {
    "3-in-1 Amusement Machine: Boxer, Kicker & Hammer": "Automat rozrywkowy 3 w 1: Boxer, Kicker i Hammer",
    "This innovative 3-in-1 arcade machine combines three popular strength-testing games in one compact unit — Boxer, Kicker, and Hammer.": "Ten innowacyjny automat 3 w 1 łączy trzy popularne gry mierzące siłę w jednym kompaktowym urządzeniu — Boxer, Kicker i Hammer.",
    "Players can test their power by choosing between punching, kicking, or hammering modes, all integrated into a single durable and eye-catching cabinet.": "Gracze mogą sprawdzić swoją siłę, wybierając uderzanie pięścią, kopanie lub uderzanie młotem — wszystko w jednej trwałej i przyciągającej wzrok obudowie.",
    "The machine features a modern design with LED lighting, high-quality sensors for accurate scoring": "Automat wyróżnia się nowoczesnym wzornictwem z oświetleniem LED oraz wysokiej jakości czujnikami zapewniającymi dokładny pomiar wyniku",
    "Perfect for bars, amusement centers, and events, it offers maximum entertainment value while saving space.": "Idealny do barów, centrów rozrywki i na wydarzenia — zapewnia maksimum rozrywki, jednocześnie oszczędzając miejsce.",
    "Built for heavy use, the 3-in-1 Boxer/Kicker/Hammer guarantees fun, competition, and excitement for players of all ages.": "Zaprojektowany do intensywnego użytkowania Boxer/Kicker/Hammer 3 w 1 gwarantuje zabawę, rywalizację i emocje graczom w każdym wieku.",
    "Bill acceptor.": "Akceptor banknotów.",
    "Nayax device.": "Urządzenie Nayax.",
    "Ticket dispenser.": "Dyspenser biletów.",
    "Custom sticker and branding (Advance orders).": "Indywidualne naklejki i oznakowanie marki (zamówienie z wyprzedzeniem).",
    "Silent mode (Advance orders).": "Tryb cichy (zamówienie z wyprzedzeniem).",
    "Height": "Wysokość",
    "Width": "Szerokość",
    "Length": "Długość",
    "Weight": "Waga",
    "Offers two exciting challenges in one compact machine with vibrant LED lights that bring extra attraction. Press the top Start button to release the punchball and test your strength or hit the bottom button to kick the football and show off your skills. Double the action, all in one game!": "Dwa ekscytujące wyzwania w jednym kompaktowym automacie, z intensywnym oświetleniem LED, które dodatkowo przyciąga uwagę. Naciśnij górny przycisk Start, aby zwolnić gruszkę bokserską i sprawdzić swoją siłę, lub dolny przycisk, aby kopnąć piłkę i pokazać swoje umiejętności. Podwójna akcja w jednej grze!",
    "Thrilling gameplay: Captivates players with exciting challenges that test their strength, ensuring they stay engaged and keep coming back for more fun.": "Ekscytująca rozgrywka: Wciąga graczy wyzwaniami sprawdzającymi ich siłę, utrzymuje zaangażowanie i zachęca do powrotu po kolejną porcję zabawy.",
    "Unmatched Durability & Convenience: Built with premium electronics and tough mechanics, making it perfect for high-traffic venues. Plus, it accepts bills, coins, cards, and tokens for seamless transactions.": "Niezrównana trwałość i wygoda: Wysokiej klasy elektronika i wytrzymała mechanika sprawiają, że urządzenie doskonale nadaje się do obiektów o dużym ruchu. Ponadto przyjmuje banknoty, monety, karty i żetony, zapewniając sprawne płatności.",
    "Boost Your Profits: Adjustable difficulty settings and free play modes to increase engagement and driving higher revenue.": "Zwiększ swoje zyski: Regulacja poziomu trudności i tryby gry bezpłatnej zwiększają zaangażowanie i przychody.",
    "This versatile machine offers three exciting challenges boxing, kicking and a prize feature all in one compact design. Equipped with vibrant LED lights for added attraction, players can showcase their strength and skill by hitting the punchball or football and get special prizes with extra motivation and excitement. It’s triple the action in one game!": "Ten wszechstronny automat oferuje trzy ekscytujące wyzwania: boksowanie, kopanie i funkcję nagród — wszystko w jednej kompaktowej konstrukcji. Intensywne oświetlenie LED dodatkowo przyciąga uwagę, a gracze mogą pokazać siłę i umiejętności, uderzając gruszkę bokserską lub kopiąc piłkę, oraz zdobywać specjalne nagrody, które zwiększają motywację i emocje. Potrójna akcja w jednej grze!",
    "This machine combines two exciting games in one: boxing and kicking! Perfectly designed for younger players, this machine brings twice the fun in a single unit, making it ideal for family-friendly venues.": "Ten automat łączy dwie ekscytujące gry w jednej: boksowanie i kopanie! Zaprojektowany specjalnie dla młodszych graczy, zapewnia podwójną zabawę w jednym urządzeniu i idealnie nadaje się do obiektów rodzinnych.",
    "2-in-1 Action: Combines boxing and kicking games for double the excitement.": "Akcja 2 w 1: Połączenie boksowania i kopania zapewnia podwójne emocje.",
    "Kid-Friendly Design: Tailored for children with a safe and easy-to-use layout.": "Konstrukcja przyjazna dzieciom: Dostosowany do dzieci, bezpieczny i łatwy w obsłudze układ.",
    "Bright LED Lights: Eye-catching lights make gameplay even more fun.": "Jasne oświetlenie LED: Przyciągające wzrok światła sprawiają, że gra jest jeszcze ciekawsza.",
    "Flexible Payment Options: Supports multiple payment types, including bills, coins, cards, and tokens, making it adaptable to any currency.": "Elastyczne opcje płatności: Obsługa banknotów, monet, kart i żetonów umożliwia dostosowanie do dowolnej waluty.",
    "Adjustable Play Mode: Set the game to different levels or free play mode to match the age and skill level of the players.": "Regulowany tryb gry: Ustaw różne poziomy lub tryb gry bezpłatnej, aby dopasować grę do wieku i umiejętności graczy.",
    "This machine combines three fun games in one: boxing, kicking and a prize feature! Designed for young players, it keeps kids engaged with exciting challenges and vibrant LED lights, making it a perfect fit for family venues.": "Ten automat łączy trzy zabawy w jednej: boksowanie, kopanie i funkcję nagród! Zaprojektowany dla młodych graczy, przyciąga dzieci ekscytującymi wyzwaniami i intensywnym oświetleniem LED, dzięki czemu doskonale pasuje do obiektów rodzinnych.",
    "3-in-1 Action: Offers boxing, kicking a prize reward option for extra excitement.": "Akcja 3 w 1: Boksowanie, kopanie i możliwość zdobywania nagród zapewniają dodatkowe emocje.",
    "Kid-Friendly Design: Safe, engaging and easy-to-use for children.": "Konstrukcja przyjazna dzieciom: Bezpieczna, angażująca i łatwa w obsłudze dla dzieci.",
    "Bright LED Lights: Colorful lights add to the fun and attraction.": "Jasne oświetlenie LED: Kolorowe światła zwiększają atrakcyjność i radość z gry.",
    "Immersive Experience: Captivating gameplay that challenges strength, keeping customers coming back for more.": "Rywalizacja na wynik, która od razu angażuje graczy. Klasyczny pomiar siły zachęca do bicia rekordów, porównywania rezultatów i kolejnych rozgrywek.",
    "Built to Last: Designed with robust electronics and mechanics, perfect for high-traffic venues looking for reliable performance.": "Trwała konstrukcja: Solidna elektronika i mechanika, idealne dla obiektów o dużym ruchu, którym zależy na niezawodnym działaniu.",
    "Multible Payment Options: Supports a variety of payment methods, including bills, coins, cards, and tokens—suitable for any currency.": "Różne opcje płatności: Obsługuje banknoty, monety, karty i żetony — z możliwością dostosowania do dowolnej waluty.",
    "Revenue Booster: Adjustable difficulty levels and free play mode to engage diverse audiences and maximize profits.": "Zwiększanie przychodów: Regulowane poziomy trudności i tryb gry bezpłatnej angażują różne grupy odbiorców i maksymalizują zyski.",
    "Card reader.": "Czytnik kart.",
    "2 meter power cable.": "Przewód zasilający o długości 2 metrów.",
    "Protective cover.": "Pokrowiec ochronny.",
    "Custom sticker and branding.": "Indywidualne naklejki i oznakowanie marki.",
    "LED lighting variation available.": "Dostępny wariant oświetlenia LED.",
    "MULTIPLAYER BOXER MACHINE": "WIELOOSOBOWY AUTOMAT BOKSERSKI",
    "Boxer Fist is our new exciting multiplayer boxing arcade machine, built to entertain and challenge groups in any arcade, FEC, or entertainment venue. With its eye-catching LED lighting, modern decals, and robust construction, this machine invites competitive fun and repeat play.": "Boxer Fist to nasz nowy, ekscytujący wieloosobowy automat bokserski, stworzony, by bawić i stawiać wyzwania grupom w salonach gier, rodzinnych centrach rozrywki i innych obiektach rozrywkowych. Przyciągające wzrok oświetlenie LED, nowoczesne naklejki i solidna konstrukcja zachęcają do rywalizacji i kolejnych rozgrywek.",
    "Multiplayer Ready: Supports group challenges and head-to-head punching competitions. Perfect for friends, events, and team contests.": "Gotowy do gry wieloosobowej: Umożliwia wyzwania grupowe i bezpośrednią rywalizację w uderzeniach. Idealny dla przyjaciół, na wydarzenia i zawody drużynowe.",
    "Full LED Integration: Illuminated edges, buttons, and scoring panel to maximize visibility and energy.": "Pełna integracja LED: Podświetlane krawędzie, przyciski i panel wyników zapewniają maksymalną widoczność i energię.",
    "Heavy-Duty Frame: Reinforced body and impact-resistant build for long-term durability.": "Wytrzymała rama: Wzmocniona obudowa i konstrukcja odporna na uderzenia zapewniają długotrwałą wytrzymałość.",
    "Operator-Friendly: Reliable electronics, easy maintenance access, and cashless-ready setup.": "Przyjazny operatorowi: Niezawodna elektronika, łatwy dostęp serwisowy i przygotowanie do płatności bezgotówkowych.",
    "One of the latest additions to our lineup, Kids Combat offers an exciting, safe boxing experience for younger players. With its bold design and enhanced features, it’s ideal for arcades and family-friendly venues.": "Kids Combat, jeden z najnowszych modeli w naszej ofercie, zapewnia młodszym graczom ekscytującą i bezpieczną zabawę bokserską. Dzięki wyrazistemu wzornictwu i udoskonalonym funkcjom idealnie nadaje się do salonów gier i obiektów rodzinnych.",
    "Brand new Design: Fresh, engaging look tailored for kids.": "Zupełnie nowy design: Świeży, atrakcyjny wygląd dostosowany do dzieci.",
    "Safe and fun Gameplay: Perfect for younger players to safely enjoy the excitement of boxing.": "Bezpieczna i przyjemna rozgrywka: Idealna dla młodszych graczy, którzy chcą bezpiecznie cieszyć się emocjami boksowania.",
    "This machine is designed specifically for younger players, providing a fun and safe way to enjoy the excitement of a boxing game. With bright colors and engaging gameplay, it’s perfect for family-oriented locations.": "Ten automat został zaprojektowany specjalnie dla młodszych graczy i zapewnia bezpieczny oraz przyjemny sposób na poznanie emocji gry bokserskiej. Dzięki jaskrawym kolorom i angażującej rozgrywce doskonale sprawdza się w miejscach nastawionych na rodziny.",
    "Kid-Friendly Design: A smaller size and layout specifically made for children to enjoy.": "Konstrukcja przyjazna dzieciom: Mniejszy rozmiar i układ zaprojektowany specjalnie z myślą o zabawie dzieci.",
    "The Boxer Flash Gift offers an exciting twist by combining the classic boxing challenge with a rewarding gift feature. With bright LED lights and engaging gameplay.": "Boxer Flash Gift urozmaica klasyczne wyzwanie bokserskie funkcją zdobywania nagród. Oferuje jasne oświetlenie LED i angażującą rozgrywkę.",
    "Strength Challenge + Prizes: Players punch the bag, score high, and win special prizes.": "Wyzwanie siłowe i nagrody: Gracze uderzają w gruszkę, zdobywają wysokie wyniki i wygrywają specjalne nagrody.",
    "Flexible Payment Options: Supports a variety of payment methods, including bills, coins, cards, and tokens suitable for any currency.": "Elastyczne opcje płatności: Obsługuje banknoty, monety, karty i żetony, z możliwością dostosowania do dowolnej waluty.",
    "It is a classic strength-testing game that challenges players to hit as hard as they can. Perfect for amusement parks, arcades, and family entertainment centers (FECs), this timeless game is fun, competitive, and draws in crowds with its vibrant LED lights.": "To klasyczna gra mierząca siłę, w której gracze starają się uderzyć jak najmocniej. Idealna do parków rozrywki, salonów gier i rodzinnych centrów rozrywki (FEC), ta ponadczasowa gra zapewnia zabawę i rywalizację, a intensywne oświetlenie LED przyciąga tłumy.",
    "Power Strike Challenge: Swing the hammer and see how high you can score.": "Wyzwanie mocnego uderzenia: Zamachnij się młotem i sprawdź, jak wysoki wynik uzyskasz.",
    "Bright LED Lights: Eye-catching lights that enhance the excitement and attract attention.": "Jasne oświetlenie LED: Przyciągające wzrok światła zwiększają emocje i zwracają uwagę.",
    "Ticket Option: Can be set to reward tickets, making it ideal for redemption venues.": "Opcja biletowa: Możliwość przyznawania biletów jako nagrody sprawia, że urządzenie idealnie nadaje się do obiektów z grami redemption.",
    "Adjustable Difficulty & Free Play Mode: Suited for players of all ages and skill levels.": "Regulacja trudności i tryb gry bezpłatnej: Dla graczy w każdym wieku i na każdym poziomie umiejętności.",
    "This machine offers a thrilling and dynamic game designed for players who want to test their kicking strength and accuracy Perfect for both kids and adults, it’s a great addition to arcades, sports bars, and family entertainment centers.": "Ten automat oferuje ekscytującą, dynamiczną grę dla osób, które chcą sprawdzić siłę i celność kopnięcia. Idealny zarówno dla dzieci, jak i dorosłych, stanowi świetne uzupełnienie salonów gier, barów sportowych i rodzinnych centrów rozrywki.",
    "Kick Challenge: Players kick the ball to score points, testing their power and precision.": "Wyzwanie kopnięcia: Gracze kopią piłkę, aby zdobywać punkty, sprawdzając swoją siłę i precyzję.",
    "Adjustable Difficulty & Free Play Mode: Customizable for different ages and skill levels.": "Regulacja trudności i tryb gry bezpłatnej: Możliwość dostosowania do różnych grup wiekowych i poziomów umiejętności.",
    "The Boxer Gift offers an exciting twist by combining the classic boxing challenge with a rewarding gift feature. With bright LED lights and engaging gameplay.": "Boxer Gift urozmaica klasyczne wyzwanie bokserskie funkcją zdobywania nagród. Oferuje jasne oświetlenie LED i angażującą rozgrywkę.",
    "Small inflatable castles for children": "Małe dmuchane zamki dla dzieci",
    "The Mini XS inflatables are a fantastic attraction for the youngest guests at your event! These colourful inflatables instantly catch children’s attention and quickly become their favourite place to play.": "Dmuchane zamki Mini XS to fantastyczna atrakcja dla najmłodszych gości Twojego wydarzenia! Te kolorowe dmuchańce od razu przyciągają uwagę dzieci i szybko stają się ich ulubionym miejscem zabawy.",
    "Kids know they can enjoy unlimited fun inside. In the compact bouncy castle, they can jump, play, and burn off energy for hours. Some of our children’s inflatables also come with built-in slides.": "Dzieci wiedzą, że w środku czeka na nie nieograniczona zabawa. W kompaktowym dmuchanym zamku mogą godzinami skakać, bawić się i spożytkować energię. Niektóre z naszych dmuchańców dla dzieci mają również wbudowane zjeżdżalnie.",
    "Our small bouncy castles are always a big hit with children!": "Nasze małe dmuchane zamki zawsze cieszą się ogromnym powodzeniem wśród dzieci!",
    "The Golden air hockey is a new version of our bestseller indoor airhoockey.": "Cymbergaj Golden to nowa wersja naszego bestsellerowego modelu do wnętrz.",
    "Golden table boasts a refined and elegant design that blends seamlessly with any interior. Its subtle color palette, paired with tasteful golden accents, gives it a timeless appeal that never goes out of style. This table is not only a source of entertainment but also a sophisticated addition to any game room or leisure space.": "Stół Golden wyróżnia się dopracowanym, eleganckim wzornictwem, które harmonijnie pasuje do każdego wnętrza. Subtelna kolorystyka w połączeniu z gustownymi złotymi akcentami nadaje mu ponadczasowy wygląd, który nigdy nie wychodzi z mody. Ten stół to nie tylko źródło rozrywki, ale także stylowy dodatek do każdego pokoju gier lub przestrzeni wypoczynkowej.",
    "Solid construction proven by over 20 years of experience. Modern software allowing you to easily personalize different settings.": "Solidna konstrukcja sprawdzona przez ponad 20 lat doświadczenia. Nowoczesne oprogramowanie umożliwia łatwą personalizację różnych ustawień.",
    "Please note:": "Uwaga:",
    "The lamp shown is an optional accessory - it is not sold as standard equipment.": "Przedstawiona lampa jest wyposażeniem opcjonalnym — nie jest sprzedawana w standardzie.",
    "stainless perforated metal playfield": "Perforowane pole gry z metalu nierdzewnego",
    "system of lighting LED in playfield": "System oświetlenia LED w polu gry",
    "system of lighting LED in legs": "System oświetlenia LED w nogach",
    "digital score display in standard/LED lamp optional": "Cyfrowy wyświetlacz wyników w standardzie / lampa LED opcjonalnie",
    "polycarbonate barrier in the middle of playfield": "Poliwęglanowa przegroda na środku pola gry",
    "air pump 260 W": "Pompa powietrza 260 W",
    "power supply 230v/50Hz": "Zasilanie 230 V / 50 Hz",
    "power consumption 82 W (demo mode), 260 W (game mode)": "Pobór mocy 82 W (tryb demonstracyjny), 260 W (tryb gry)",
    "accessories included: 4 mallets, 6 pucks, 100 tokens (if programmed for tokens)": "Akcesoria w zestawie: 4 odbijaki, 6 krążków, 100 żetonów (jeśli zaprogramowano na żetony)",
    "Warranty: 12 months for enterprises, 24 months for consumers": "Gwarancja: 12 miesięcy dla przedsiębiorców, 24 miesiące dla konsumentów",
    "optional - ticket dispenser, bill acceptor, card reader": "Opcjonalnie — dyspenser biletów, akceptor banknotów, czytnik kart",
    "Product: LxWxH // Weight": "Produkt: dł. × szer. × wys. // waga",
    "Package: LxWxH // Weight": "Opakowanie: dł. × szer. × wys. // waga",
    "AIR HOCKEY ARCTIC is a 100% waterproof device that can be used outdoors all year round, just like indoors. It is one of the most popular machines. Solid construction proven by over 20 years of experience. Modern software allows you to easily personalize different settings.": "AIR HOCKEY ARCTIC to w 100% wodoodporne urządzenie, które może być używane przez cały rok na zewnątrz, tak samo jak wewnątrz. To jeden z najpopularniejszych automatów. Solidna konstrukcja sprawdzona przez ponad 20 lat doświadczenia. Nowoczesne oprogramowanie pozwala łatwo personalizować różne ustawienia.",
    "COMESTERO RM5 or NRI electronic coin acceptor": "Elektroniczny wrzutnik monet COMESTERO RM5 lub NRI",
    "polycarbonate perforated playfield": "Perforowane pole gry z poliwęglanu",
    "polycarbonate top frame around the playfield with a lighting system": "Górna rama z poliwęglanu wokół pola gry z systemem oświetlenia",
    "polycarbonate barrier on both sides and in the center of a playfield": "Poliwęglanowa przegroda po obu stronach i na środku pola gry",
    "LED lightning system in the playfield": "System oświetlenia LED w polu gry",
    "LED lightning system in the legs": "System oświetlenia LED w nogach",
    "digital score display for each player": "Cyfrowy wyświetlacz wyniku dla każdego gracza",
    "standard power supply 230v/50Hz": "Standardowe zasilanie 230 V / 50 Hz",
    "power consumption 60 W (demo mode), 390 W (game mode)": "Pobór mocy 60 W (tryb demonstracyjny), 390 W (tryb gry)",
    "accessories included: 4 mallets, 6 pucks, 100 tokens (if token-programmed)": "Akcesoria w zestawie: 4 odbijaki, 6 krążków, 100 żetonów (jeśli zaprogramowano na żetony)",
    "warranty: 12 months for enterprises, 24 months for consumers": "Gwarancja: 12 miesięcy dla przedsiębiorców, 24 miesiące dla konsumentów",
    "Check out our brand new airhockey Matrix! LED display isn't only there to look amazing - it also communicates game updates and events, showing 'SCORE!' when a goal is scored, and a commiserating 'OH NO!' when you concede a goal. Countdown timers at each end keep you informed of time left to play, and the whole display flexes, colour-shifts and pulsates in perfect sync with your game. Customisable operator settings allow you to configure the table exactly as you want it and the 260w air pump creates a cushion of air across the playfield for the fastest speeds.": "Poznaj nasz zupełnie nowy cymbergaj Matrix! Wyświetlacz LED nie tylko świetnie wygląda — przekazuje też informacje o przebiegu gry, pokazując „SCORE!” po zdobyciu gola i współczujące „OH NO!”, gdy stracisz bramkę. Liczniki na obu końcach informują o pozostałym czasie, a cały wyświetlacz zmienia wygląd, kolory i pulsuje w idealnej synchronizacji z grą. Konfigurowalne ustawienia operatora pozwalają dopasować stół do własnych potrzeb, a pompa powietrza o mocy 260 W tworzy poduszkę powietrzną nad polem gry, zapewniając największe prędkości.",
    "Air hockey has been around for a long time, with only rarely a major paradigm shift in design or functionality. Now the Matrix knocks the sector out of the park with its integrated LED displays and systems. If you're looking for a truly spectacular centrepiece for your venue - or even for your private games room - then take the red pill and enter the Matrix now!": "Cymbergaj istnieje od dawna, a duże przełomy we wzornictwie lub funkcjonalności zdarzają się rzadko. Teraz Matrix wyznacza nowy poziom dzięki zintegrowanym wyświetlaczom i systemom LED. Jeśli szukasz naprawdę spektakularnej głównej atrakcji do swojego lokalu — lub nawet prywatnego pokoju gier — wybierz czerwoną pigułkę i wejdź do Matrixa już teraz!",
    "Futuristic commercial air hockey table.": "Futurystyczny komercyjny stół do cymbergaja.",
    "Suitable for amusement arcades, commercial venues & homes.": "Do salonów gier, obiektów komercyjnych i domów.",
    "Unique LED matrix light display incorporating game commentary.": "Wyjątkowy matrycowy wyświetlacz LED z komentarzami do gry.",
    "LED score displays and message updates.": "Wyświetlacze LED z wynikami i komunikatami.",
    "Sound system with in-game audio.": "System dźwiękowy z efektami podczas gry.",
    "Electronic coin acceptor included - freeplay game as an option.": "Elektroniczny wrzutnik monet w zestawie — opcjonalny tryb gry bezpłatnej.",
    "Includes four pushers and six pucks.": "W zestawie cztery odbijaki i sześć krążków.",
    "New basketball machine from WIK, compact size allows pass through 80cm wide doorways. Customized height 248-310cm.": "Nowy automat do koszykówki firmy WIK. Kompaktowe wymiary umożliwiają przejazd przez drzwi o szerokości 80 cm. Wysokość dostosowywana w zakresie 248–310 cm.",
    "electronic coin acceptor COMESTERO RM5": "Elektroniczny wrzutnik monet COMESTERO RM5",
    "construction made of metal and laminated polycarbonate": "Konstrukcja z metalu i laminowanego poliwęglanu",
    "digital score, credit and record display": "Cyfrowy wyświetlacz wyniku, kredytów i rekordu",
    "linking option": "Opcja łączenia urządzeń",
    "moving basket": "Ruchomy kosz",
    "5 balls included": "5 piłek w zestawie",
    "easy moving system (6 wheels with blockade system)": "System łatwego przemieszczania (6 kół z blokadą)",
    "easy and fast assembly": "Łatwy i szybki montaż",
    "power supply 230V/50Hz": "Zasilanie 230 V / 50 Hz",
    "power consumption: 105 W (demo mode), 180 W (game mode)": "Pobór mocy: 105 W (tryb demonstracyjny), 180 W (tryb gry)",
    "warranty: 12 months": "Gwarancja: 12 miesięcy",
    "optional: ticket dispenser, bill acceptor, card reader": "Opcjonalnie: dyspenser biletów, akceptor banknotów, czytnik kart",
    "Our weatherproof basketball arcade machines can be used outdoor all year round. The game has four levels of difficulty and comes with a set of five balls. Depending on the mode selected, the basket can be movable.": "Nasze odporne na warunki atmosferyczne automaty do koszykówki mogą być używane na zewnątrz przez cały rok. Gra ma cztery poziomy trudności i jest dostarczana z zestawem pięciu piłek. W zależności od wybranego trybu kosz może się poruszać.",
    "It is very easy to assemble and transport.": "Montaż i transport są bardzo łatwe.",
    "Basketball is a game for all ages with both kids and adults loving this game. Players can play in a group and compete for the best score (linking option). It's a high quality long lasting machine. WIK is a leader in making the basketball arcade machines with years of experience. This is a crowd pleaser that never ceases to provide fun.": "Koszykówka to gra dla osób w każdym wieku, uwielbiana zarówno przez dzieci, jak i dorosłych. Gracze mogą grać w grupie i rywalizować o najlepszy wynik (opcja łączenia urządzeń). To wysokiej jakości, trwały automat. WIK jest liderem produkcji automatów do koszykówki z wieloletnim doświadczeniem. To atrakcja lubiana przez publiczność, która nie przestaje dostarczać zabawy.",
    "east and fast assembly": "Łatwy i szybki montaż",
    "power conumption: 105 W (demo mode), 180 W (game mode)": "Pobór mocy: 105 W (tryb demonstracyjny), 180 W (tryb gry)"
  },
  "colors": {
    "Black": "Czarny",
    "Blue": "Niebieski",
    "Red": "Czerwony",
    "Yellow": "Żółty",
    "White": "Biały",
    "Orange": "Pomarańczowy",
    "Green": "Zielony",
    "Pink": "Różowy",
    "Brown": "Brązowy",
    "Graphite": "Grafitowy",
    "Golden": "Golden",
    "Arctic": "Arctic",
    "Matrix": "Matrix",
    "Compact": "Compact",
    "Standard": "Standard",
    "Kids": "Kids",
    "Purple": "Fioletowy",
    "Silver": "Srebrny",
    "Multicolour": "Wielokolorowy",
    "Standard · Matte black": "Standard · matowa czerń",
    "Combat · Matte black": "Combat · matowa czerń",
    "Double Hit · Matte black": "Double Hit · matowa czerń",
    "Comic artwork · Red": "Grafika Comic · czerwony",
    "Current model": "Aktualny model",
    "Current range": "Aktualna oferta",
    "Dino with Slide": "Dino ze zjeżdżalnią",
    "Circus with Slide": "Cyrk ze zjeżdżalnią",
    "Jungle with Roof": "Dżungla z dachem",
    "Jungle with Slide": "Dżungla ze zjeżdżalnią",
    "Pirates with Roof": "Piraci z dachem",
    "Pirates with Slide": "Piraci ze zjeżdżalnią",
    "Princess with Roof": "Księżniczka z dachem",
    "Princess with Slide": "Księżniczka ze zjeżdżalnią",
    "Sea with Roof": "Morze z dachem",
    "Sea with Slide": "Morze ze zjeżdżalnią",
    "Artwork 01 · Black": "Wzór 01 · czarny",
    "Artwork 01 · Blue": "Wzór 01 · niebieski",
    "Artwork 01 · Orange": "Wzór 01 · pomarańczowy",
    "Artwork 01 · Red": "Wzór 01 · czerwony",
    "Artwork 01 · White": "Wzór 01 · biały",
    "Artwork 01 · Yellow": "Wzór 01 · żółty",
    "Artwork 02 · Black": "Wzór 02 · czarny",
    "Artwork 02 · Blue": "Wzór 02 · niebieski",
    "Artwork 02 · Orange": "Wzór 02 · pomarańczowy",
    "Artwork 02 · Red": "Wzór 02 · czerwony",
    "Artwork 02 · White": "Wzór 02 · biały",
    "Artwork 02 · Yellow": "Wzór 02 · żółty",
    "Artwork 03 · Black": "Wzór 03 · czarny",
    "Artwork 03 · Blue": "Wzór 03 · niebieski",
    "Artwork 03 · Orange": "Wzór 03 · pomarańczowy",
    "Artwork 03 · Red": "Wzór 03 · czerwony",
    "Artwork 03 · White": "Wzór 03 · biały",
    "Artwork 03 · Yellow": "Wzór 03 · żółty"
  }
};
