const products={
'monster-3in1':{name:'Monster 3 in 1',cat:'COMBO MACHINE · NEW 2026',desc:'Trzy gry siłowe w jednym urządzeniu: boxer, kicker i hammer. Konstrukcja przeznaczona do lokali, centrów rozrywki i eventów, gdzie liczy się maksymalna wartość rozrywkowa przy ograniczonej powierzchni.',img:null,spec:[['Wysokość','230 cm'],['Szerokość','140 cm'],['Długość','140 cm'],['Waga','250 kg']],features:['Boxer + Kicker + Hammer w jednym urządzeniu','Oświetlenie LED','Czujniki pomiarowe','Konfiguracja pod zastosowania komercyjne'],options:['Akceptor banknotów','Nayax','Dyspenser ticketów','Custom branding','Tryb cichy']},
'double-hit':{name:'Double Hit',cat:'COMBO MACHINE',desc:'Kompaktowe urządzenie łączące dwa wyzwania: uderzenie pięścią i kopnięcie piłki. Zaprojektowane do intensywnej eksploatacji i obsługi różnych metod płatności.',img:'https://static.wixstatic.com/media/d36c49_6734792db6114266b184ac84df6a5277~mv2.jpg',spec:[['Wysokość','219 cm'],['Szerokość','85 cm'],['Długość','122 cm'],['Waga','175 kg']],features:['Dwa tryby gry w jednej obudowie','Oświetlenie LED','Regulowane ustawienia trudności','Tryb free play'],options:['Akceptor banknotów','Nayax','Dyspenser ticketów','Custom branding','Tryb cichy']},
'boxer-combat':{name:'Boxer Combat',cat:'BOXER PREMIUM',desc:'Profesjonalny boxer o wyrazistej stylistyce i konstrukcji przygotowanej do miejsc o dużym natężeniu ruchu.',img:'https://static.wixstatic.com/media/d36c49_ed71f4e5c19b444cb213986490bae519~mv2.jpg',spec:[['Wysokość','219 cm'],['Szerokość','72 cm'],['Długość','115 cm'],['Waga','121 kg']],features:['Konstrukcja do intensywnej eksploatacji','Płatności: monety, banknoty, karty i tokeny','Regulowana trudność','Tryb free play'],options:['Akceptor banknotów','Nayax','Dyspenser ticketów','Custom branding','Tryb cichy']},
'boxer-ring':{name:'Boxer Ring',cat:'BOXER PREMIUM',desc:'Boxer premium łączący klasyczną mechanikę gry siłowej z nowoczesną oprawą wizualną.',img:'https://static.wixstatic.com/media/d36c49_684306c4340c45c1804b8006822b8628~mv2.jpg',spec:[['Wysokość','219 cm'],['Szerokość','72 cm'],['Długość','115 cm'],['Waga','127 kg']],features:['Profesjonalna maszyna siłowa','Obsługa wielu metod płatności','Regulowana trudność','Tryb free play'],options:['Akceptor banknotów','Nayax','Dyspenser ticketów','Custom branding','Tryb cichy']},
'boxer-flash':{name:'Boxer Flash',cat:'BOXER PREMIUM',desc:'Dynamiczny boxer premium z mocną identyfikacją wizualną. Szczegółowe parametry tej wersji należy uzupełnić na podstawie aktualnej karty produktu.',img:'https://static.wixstatic.com/media/d36c49_082568a7673a4348b86ff39dbae04067~mv2.jpg',spec:[['Wysokość','Do uzupełnienia'],['Szerokość','Do uzupełnienia'],['Długość','Do uzupełnienia'],['Waga','Do uzupełnienia']],features:['Profesjonalny boxer','Oświetlenie produktu','Konfiguracja komercyjna','Serwis i części Pro Games'],options:['Dane opcji do aktualizacji']},
'hammer':{name:'Hammer',cat:'STRENGTH MACHINE',desc:'Urządzenie siłowe Hammer znajduje się w aktualnej ofercie Pro Games. Parametry i aktualne zdjęcia należy podpiąć po otrzymaniu zweryfikowanej karty produktu.',img:null,spec:[['Wysokość','Do uzupełnienia'],['Szerokość','Do uzupełnienia'],['Długość','Do uzupełnienia'],['Waga','Do uzupełnienia']],features:['Urządzenie siłowe','Format arcade','Przeznaczenie komercyjne'],options:['Do uzupełnienia']},
'kids':{name:'Kids Series',cat:'MACHINES FOR KIDS',desc:'Linia urządzeń dla młodszych użytkowników obejmuje m.in. Boxer Kids oraz nowsze warianty premium. W finalnej wersji warto wydzielić osobną rodzinę produktową z filtrami wieku, wymiarów i wariantów.',img:null,spec:[['Parametry','Do uzupełnienia na podstawie modelu']],features:['Dedykowane konstrukcje kids','Warianty premium w obecnej ofercie','Przeznaczenie komercyjne'],options:['Do uzupełnienia']}}
const key=new URLSearchParams(location.search).get('model')||'double-hit';const p=products[key]||products['double-hit'];document.title=`${p.name} — Pro Games Poland`;
const visual=p.img?`<img src="${p.img}" alt="${p.name} Pro Games"/>`:`<div class="detail-placeholder"><span>${p.name}</span><small>PLACEHOLDER — wgraj finalne zdjęcie produktu</small></div>`;
document.querySelector('#productDetail').innerHTML=`<section class="product-detail"><div class="detail-visual reveal in">${visual}<div class="led-line"></div></div><div class="detail-info"><p class="kicker">${p.cat}</p><h1>${p.name}</h1><p class="detail-lead">${p.desc}</p><div class="detail-actions"><a class="btn btn-primary" href="/#contact">Zapytaj o cenę</a><a class="btn btn-ghost" href="#spec">Pobierz specyfikację*</a></div><small>* przycisk gotowy do podpięcia aktualnego PDF.</small></div></section><section class="detail-sections" id="spec"><div><p class="kicker">KEY FEATURES</p><h2>Designed for<br>professional operation.</h2></div><ul class="feature-list">${p.features.map(x=>`<li>${x}</li>`).join('')}</ul><div class="spec-table"><h3>Parametry techniczne</h3>${p.spec.map(s=>`<div><span>${s[0]}</span><b>${s[1]}</b></div>`).join('')}</div><div class="spec-table"><h3>Opcjonalne wyposażenie</h3>${p.options.map(o=>`<div><span>${o}</span><b>+</b></div>`).join('')}</div></section><section class="product-cta"><p class="kicker">READY TO TALK?</p><h2>Build your next<br>entertainment experience.</h2><a class="btn btn-primary" href="/#contact">Wyślij zapytanie</a></section>`;
