import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const COLORS=[{name:'Black',key:'black',hex:'#13161a'},{name:'White',key:'white',hex:'#eef1f4'},{name:'Red',key:'red',hex:'#d2262e'},{name:'Orange',key:'orange',hex:'#ee6c14'},{name:'Blue',key:'blue',hex:'#0789e8'},{name:'Yellow',key:'yellow',hex:'#efc215'}];
const BODY_NODES=['BODY_MAIN','LEFT_PANEL','RIGHT_PANEL','BODY_COLUMN','BACK_PANEL','TOP_SECTION','TOP_LIP','FRONT_FRAME_TOP','FRONT_FRAME_BOTTOM','FRONT_FRAME_LEFT','FRONT_FRAME_RIGHT','REAR_SERVICE_DOOR','REAR_SERVICE_LOWER'];
const EQUIPMENT={coin_acceptor:['COIN_ACCEPTOR'],banknote_acceptor:['BANKNOTE_ACCEPTOR'],card_reader:['CARD_READER'],ticket_dispenser:['TICKET_DISPENSER'],capsule_dispenser:['CAPSULE_DISPENSER','CAPSULE_BASE']};
const SURFACE={front:'CUSTOM_FRONT',left:'CUSTOM_LEFT',right:'CUSTOM_RIGHT'};
const defaultBrand=()=>({enabled:false,fileName:null,dataUrl:null,x:0,y:0,scale:1,rotation:0});
const state={product:'Double Strike 2',color:'blue',equipment:{coin_acceptor:true,banknote_acceptor:false,card_reader:false,ticket_dispenser:false,capsule_dispenser:false},branding:{front:defaultBrand(),left:defaultBrand(),right:defaultBrand()},activeSurface:'front',configId:'PGC-DS2-000000'};
let renderer,scene,camera,controls,machine,started=false,resizeObserver;const brandRuntime={front:null,left:null,right:null};
const defaultCamera={position:new THREE.Vector3(2.65,1.60,-3.15),target:new THREE.Vector3(0,1.08,-.03)};
function node(name){return machine?.getObjectByName(name)||null}
function initSwatches(){const h=$('#colorSwatches');h.innerHTML='';for(const c of COLORS){const b=document.createElement('button');b.className='swatch'+(c.key===state.color?' active':'');b.style.background=c.hex;b.dataset.color=c.key;b.title=c.name;b.setAttribute('aria-label',c.name);b.addEventListener('click',()=>setColor(c.key));h.appendChild(b)}}
function setColor(key,update=true){state.color=key;const c=COLORS.find(x=>x.key===key)||COLORS[4];for(const n of BODY_NODES){const o=node(n);if(o?.material){o.material=o.material.clone();o.material.color.set(c.hex);o.material.needsUpdate=true}}$$('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.color===key));$('#selectedColorName').textContent=c.name;if(update)updateSummary()}
function fitInitialView(){camera.position.copy(defaultCamera.position);controls.target.copy(defaultCamera.target);controls.update()}
function resize(){const h=$('#viewer');if(!renderer||!h)return;const w=Math.max(1,h.clientWidth),he=Math.max(1,h.clientHeight);renderer.setSize(w,he,false);camera.aspect=w/he;camera.updateProjectionMatrix()}
function createDisplay(){const mesh=node('DISPLAY');if(!mesh)return;const canvas=document.createElement('canvas');canvas.width=640;canvas.height=280;const ctx=canvas.getContext('2d');ctx.fillStyle='#1b0205';ctx.fillRect(0,0,640,280);ctx.shadowBlur=28;ctx.shadowColor='#ff1111';ctx.fillStyle='#ff1717';ctx.font='900 190px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('777',320,150);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;mesh.material=new THREE.MeshStandardMaterial({map:tex,emissiveMap:tex,emissive:new THREE.Color('#ff1818'),emissiveIntensity:.7,roughness:.26,metalness:0,side:THREE.DoubleSide});window.PRO_GAMES_CREATOR=window.PRO_GAMES_CREATOR||{};window.PRO_GAMES_CREATOR.setDisplayCanvas=(draw)=>{ctx.clearRect(0,0,640,280);draw(ctx,canvas);tex.needsUpdate=true}}
function createBrandRuntime(){for(const s of ['front','left','right']){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=640;const ctx=canvas.getContext('2d');const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;const mesh=node(SURFACE[s]);if(mesh){mesh.material=new THREE.MeshBasicMaterial({map:texture,transparent:true,side:THREE.DoubleSide,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-3});mesh.renderOrder=20;mesh.visible=false}brandRuntime[s]={canvas,ctx,texture,image:null};renderBranding(s)}}
function renderBranding(s){const rt=brandRuntime[s];if(!rt)return;const b=state.branding[s],{canvas,ctx}=rt;ctx.clearRect(0,0,canvas.width,canvas.height);if(b.enabled&&rt.image){const img=rt.image,fit=Math.min(canvas.width/img.naturalWidth,canvas.height/img.naturalHeight)*.66*b.scale,w=img.naturalWidth*fit,h=img.naturalHeight*fit;ctx.save();ctx.translate(canvas.width/2+b.x*canvas.width*.30,canvas.height/2+b.y*canvas.height*.30);ctx.rotate(b.rotation*Math.PI/180);ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore()}rt.texture.needsUpdate=true;const m=node(SURFACE[s]);if(m)m.visible=!!b.enabled}
function readData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function loadBrand(s,url,name){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>{brandRuntime[s].image=img;Object.assign(state.branding[s],{dataUrl:url,fileName:name,enabled:true});renderBranding(s);res()};img.onerror=rej;img.src=url})}
async function handleBrand(file){if(!file)return;if(file.size>8*1024*1024)return alert('Please use a branding image under 8 MB for this web prototype.');await loadBrand(state.activeSurface,await readData(file),file.name);syncBrand();updateSummary()}
function syncBrand(){const b=state.branding[state.activeSurface];$('#brandX').value=Math.round(b.x*100);$('#brandY').value=Math.round(b.y*100);$('#brandScale').value=Math.round(b.scale*100);$('#brandRotation').value=b.rotation;$('#xOut').textContent=Math.round(b.x*100);$('#yOut').textContent=Math.round(b.y*100);$('#scaleOut').textContent=Math.round(b.scale*100)+'%';$('#rotationOut').textContent=Math.round(b.rotation)+'°';$('#brandFileInfo').textContent=b.fileName?`${b.fileName} · ${state.activeSurface.toUpperCase()}`:'No branding uploaded for this surface.'}
function resetSurface(s){state.branding[s]=defaultBrand();brandRuntime[s].image=null;renderBranding(s);syncBrand();updateSummary()}
function setEquipment(){for(const [k,names] of Object.entries(EQUIPMENT))for(const n of names){const o=node(n);if(o)o.visible=!!state.equipment[k]}}
const eqLabels={coin_acceptor:'Coin acceptor',banknote_acceptor:'Banknote acceptor',card_reader:'Card reader / Nayax',ticket_dispenser:'Ticket dispenser',capsule_dispenser:'Capsule dispenser'};
function selectedEq(){return Object.entries(state.equipment).filter(([,v])=>v).map(([k])=>eqLabels[k])}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).toUpperCase().padStart(8,'0').slice(0,6)}
function core(withData=true){const branding={};for(const s of ['front','left','right']){const b=state.branding[s];branding[s]={enabled:b.enabled,fileName:b.fileName,x:b.x,y:b.y,scale:b.scale,rotation:b.rotation,...(withData?{dataUrl:b.dataUrl}:{})}}return {product:state.product,color:state.color,equipment:{...state.equipment},branding}}
function updateSummary(){state.configId='PGC-DS2-'+hash(JSON.stringify(core(false)));$('#configId').textContent=state.configId;$('#summaryColor').textContent=COLORS.find(c=>c.key===state.color)?.name||state.color;const eq=selectedEq();$('#summaryEquipment').textContent=eq.length?eq.join(', '):'None';const br=Object.entries(state.branding).filter(([,b])=>b.enabled).map(([s])=>s.toUpperCase());$('#summaryBranding').textContent=br.length?br.join(' / '):'None'}
function exportConfig(){updateSummary();return {...core(true),configurationId:state.configId,prototype:{route:'/creator/',formatVersion:1,dimensionsCm:{width:142,depth:122,height:219},modelFile:'model/pro-games-double-strike-2.glb'}}}
function download(data,name,type='application/octet-stream'){const blob=data instanceof Blob?data:new Blob([data],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function saveConfig(){const c=exportConfig();download(JSON.stringify(c,null,2),`${c.configurationId}.json`,'application/json')}
async function loadConfig(file){const cfg=JSON.parse(await file.text());if(cfg.product&&cfg.product!=='Double Strike 2')throw new Error('This prototype accepts Double Strike 2 configurations only.');state.color=cfg.color||'blue';state.equipment={...state.equipment,...(cfg.equipment||{})};for(const s of ['front','left','right']){state.branding[s]={...defaultBrand(),...(cfg.branding?.[s]||{})};const b=state.branding[s];if(b.dataUrl)await loadBrand(s,b.dataUrl,b.fileName||'branding');else{brandRuntime[s].image=null;renderBranding(s)}}setColor(state.color,false);$$('[data-equipment]').forEach(i=>i.checked=!!state.equipment[i.dataset.equipment]);setEquipment();syncBrand();updateSummary()}
function resetDesign(){state.equipment={coin_acceptor:true,banknote_acceptor:false,card_reader:false,ticket_dispenser:false,capsule_dispenser:false};for(const s of ['front','left','right']){state.branding[s]=defaultBrand();brandRuntime[s].image=null;renderBranding(s)}$$('[data-equipment]').forEach(i=>i.checked=!!state.equipment[i.dataset.equipment]);setEquipment();setColor('blue',false);state.activeSurface='front';$$('.surface-tab').forEach(b=>b.classList.toggle('active',b.dataset.surface==='front'));syncBrand();fitInitialView();updateSummary()}
function zoom(mult){const d=camera.position.clone().sub(controls.target);let len=THREE.MathUtils.clamp(d.length()*mult,controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(d.normalize().multiplyScalar(len));controls.update()}
function fullPreview(on){$('#viewerShell').classList.toggle('fullscreen-preview',on);$('#closePreview').classList.toggle('is-hidden',!on);setTimeout(resize,40)}
function screenshot(){renderer.render(scene,camera);renderer.domElement.toBlob(b=>b&&download(b,`${state.configId}-preview.png`,'image/png'),'image/png',1)}
function requestModal(){const payload={configurationId:state.configId,product:state.product,color:COLORS.find(c=>c.key===state.color)?.name,equipment:selectedEq(),branding:Object.fromEntries(Object.entries(state.branding).map(([k,b])=>[k,{enabled:b.enabled,fileName:b.fileName,transform:{x:b.x,y:b.y,scale:b.scale,rotation:b.rotation}}])),previewPng:'generated by Download Preview'};$('#requestPayload').textContent=JSON.stringify(payload,null,2);$('#requestModal').classList.remove('is-hidden');window.dispatchEvent(new CustomEvent('pgc:request-config',{detail:payload}))}
function bind(){initSwatches();syncBrand();updateSummary();$$('.surface-tab').forEach(b=>b.addEventListener('click',()=>{state.activeSurface=b.dataset.surface;$$('.surface-tab').forEach(x=>x.classList.toggle('active',x===b));syncBrand()}));$('#brandingUpload').addEventListener('change',e=>handleBrand(e.target.files[0]));$('#replaceBranding').addEventListener('click',()=>$('#brandingUpload').click());$('#resetBranding').addEventListener('click',()=>resetSurface(state.activeSurface));for(const [id,key] of [['brandX','x'],['brandY','y'],['brandScale','scale'],['brandRotation','rotation']])$('#'+id).addEventListener('input',e=>{let v=+e.target.value;if(key==='x'||key==='y')v/=100;if(key==='scale')v/=100;state.branding[state.activeSurface][key]=v;renderBranding(state.activeSurface);syncBrand();updateSummary()});$$('[data-equipment]').forEach(i=>i.addEventListener('change',()=>{state.equipment[i.dataset.equipment]=i.checked;setEquipment();updateSummary()}));$('#cameraReset').addEventListener('click',fitInitialView);$('#zoomIn').addEventListener('click',()=>zoom(.86));$('#zoomOut').addEventListener('click',()=>zoom(1.16));$('#fullPreview').addEventListener('click',()=>fullPreview(true));$('#previewFullPanel').addEventListener('click',()=>fullPreview(true));$('#closePreview').addEventListener('click',()=>fullPreview(false));$('#downloadPreview').addEventListener('click',screenshot);$('#saveConfig').addEventListener('click',saveConfig);$('#loadConfig').addEventListener('change',async e=>{try{if(e.target.files[0])await loadConfig(e.target.files[0])}catch(err){alert(err.message)}e.target.value=''});$('#resetDesign').addEventListener('click',resetDesign);$('#resetTop').addEventListener('click',resetDesign);$('#requestConfig').addEventListener('click',requestModal);$('#closeModal').addEventListener('click',()=>$('#requestModal').classList.add('is-hidden'));$('#requestModal').addEventListener('click',e=>{if(e.target===$('#requestModal'))$('#requestModal').classList.add('is-hidden')});$('#copyPayload').addEventListener('click',async()=>{await navigator.clipboard.writeText($('#requestPayload').textContent);$('#copyPayload').textContent='COPIED';setTimeout(()=>$('#copyPayload').textContent='COPY PAYLOAD',1200)});$('#downloadRequest').addEventListener('click',()=>download($('#requestPayload').textContent,`${state.configId}-inquiry.json`,'application/json'));window.addEventListener('keydown',e=>{if(e.key==='Escape'){fullPreview(false);$('#requestModal').classList.add('is-hidden')}})}
async function init3D(){const host=$('#viewer');scene=new THREE.Scene();scene.background=new THREE.Color('#e7eaee');camera=new THREE.PerspectiveCamera(33,host.clientWidth/host.clientHeight,.01,100);camera.position.copy(defaultCamera.position);const mobile=matchMedia('(max-width:700px)').matches;renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.2:1.65));renderer.setSize(host.clientWidth,host.clientHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Interactive 3D model of Double Strike 2');host.prepend(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(defaultCamera.target);controls.enableDamping=true;controls.dampingFactor=.07;controls.enablePan=false;controls.minDistance=2.15;controls.maxDistance=5.6;controls.minPolarAngle=.40;controls.maxPolarAngle=1.70;scene.add(new THREE.HemisphereLight(0xffffff,0x687281,2.3));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(-2.8,4.1,-3.0);key.castShadow=!mobile;scene.add(key);const fill=new THREE.DirectionalLight(0x9bdcff,1.45);fill.position.set(3,2.5,-1.8);scene.add(fill);const rim=new THREE.DirectionalLight(0xffffff,1.25);rim.position.set(0,3,3);scene.add(rim);const ground=new THREE.Mesh(new THREE.CircleGeometry(3.8,64),new THREE.MeshStandardMaterial({color:0xdfe3e8,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=!mobile;scene.add(ground);const grid=new THREE.GridHelper(5,20,0xc4cad1,0xd7dce2);grid.position.y=.003;grid.material.transparent=true;grid.material.opacity=.3;scene.add(grid);const gltf=await new GLTFLoader().loadAsync('./model/pro-games-double-strike-2.glb');machine=gltf.scene;scene.add(machine);machine.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.receiveShadow=!mobile;if(o.material)o.material.envMapIntensity=.5}});createDisplay();createBrandRuntime();setEquipment();setColor(state.color,false);fitInitialView();$('#loader').classList.add('is-hidden');$('#modelStatus').textContent='Prototype ready';resizeObserver=new ResizeObserver(resize);resizeObserver.observe(host);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});window.PRO_GAMES_CREATOR={...(window.PRO_GAMES_CREATOR||{}),getConfiguration:()=>exportConfig(),reset:resetDesign,requestPayload:requestModal}}
export async function startCreator(){if(started)return;started=true;bind();await init3D()}
