const fs=require('fs'),assert=require('assert/strict'),{parseHTML}=require('linkedom');
const pages=JSON.parse(fs.readFileSync('build/pages.json')),origin='https://www.progamespoland.com';const byURL=new Map(pages.map(p=>[origin+p.url,p]));const titles=new Set(),descriptions=new Set();
for(const p of pages){const {document:d}=parseHTML(fs.readFileSync(p.filename,'utf8'));assert.equal(d.querySelectorAll('h1').length,1,p.url);assert.equal(d.querySelectorAll('link[rel=canonical]').length,1);assert.equal(d.querySelector('link[rel=canonical]').href,origin+p.url);assert(!titles.has(d.title),'Duplicate title '+d.title);titles.add(d.title);const description=d.querySelector('meta[name=description]').content;assert(!descriptions.has(description),'Duplicate description '+p.url);descriptions.add(description);assert(!description.endsWith('…'));assert(!d.querySelector('meta[name=robots]').content.includes('noindex'));
 for(const link of d.querySelectorAll('link[hreflang]')){const target=byURL.get(link.href);assert(target,'Unknown alternate');assert.equal(target.kind,p.kind);assert.equal(target.key,p.key);assert.equal(target.lang,link.hreflang==='x-default'?'en':link.hreflang);}
 for(const el of d.querySelectorAll('script[type="application/ld+json"]')){const o=JSON.parse(el.textContent);if(o['@type']==='Product'){assert(!o.offers&&!o.aggregateRating&&!o.review);assert(o.description);assert.equal(o.url,origin+p.url);}const s=JSON.stringify(o);assert(!/\/(pl|de|fr)\/#(?:organization|website)/.test(s),'Split identity');}
 assert.equal(d.querySelector('meta[property="og:title"]').content,d.title);assert.equal(d.querySelector('meta[property="og:description"]').content,description);
}
const sitemap=fs.readFileSync('sitemap.xml','utf8');assert.equal((sitemap.match(/<loc>/g)||[]).length,245);assert.equal((sitemap.match(/<xhtml:link /g)||[]).length,1470);for(const p of pages)assert(sitemap.includes('<loc>'+origin+p.url+'</loc>'));
console.log('PASS SEO: 245 unique titles/descriptions; single H1; canonical URLs; 1470 language alternates; sitemap; consistent structured data and social metadata.');
