const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 global.localStorage={value:null,getItem(){return this.value},setItem(k,v){this.value=v}};
 const {load,save,validate,portable}=await import('../creator/src/state.js');
 const c=load();assert.equal(c.selectedProduct,'double-strike');assert.match(c.configurationId,/^[a-f0-9-]{36}$/);c.bodyColor='#bd2235';c.selectedOptions=['wifi'];c.customGraphics.right_side={mode:'custom',src:'data:image/png;base64,AA==',name:'logo.png',scale:1.5,x:.2,y:-.3,rotation:30,fit:'fill'};save(c);assert.deepEqual(load().customGraphics,c.customGraphics);assert.equal(load().bodyColor,c.bodyColor);assert(!JSON.stringify(portable(c)).includes('base64'));assert.equal(portable(c).customGraphics.right_side.name,'logo.png');assert.throws(()=>validate({...c,bodyColor:'red;bad'}));assert.throws(()=>validate({...c,selectedProduct:'unknown'}));assert.equal(validate({...c,selectedOptions:['wifi','invalid']}).selectedOptions.length,1);assert.equal(validate({...c,customGraphics:{right_side:{...c.customGraphics.right_side,scale:999,src:'javascript:alert(1)'}}}).customGraphics.right_side.scale,3);assert.equal(validate({...c,customGraphics:{right_side:{...c.customGraphics.right_side,src:'javascript:alert(1)'}}}).customGraphics.right_side.src,undefined);
 const {buildMachine}=await import('../creator/src/model.js');const {Box3,Vector3}=await import('three');const demo=buildMachine();const size=n=>new Box3().setFromObject(demo.getObjectByName(n)).getSize(new Vector3());assert(Math.abs(size('body_column').x-.55)<.001);assert(Math.abs(size('metal_platform').x-1.3)<.001);assert(Math.abs(size('body_column').y-1.47)<.001);
 const {NodeIO}=await import('@gltf-transform/core'),{ALL_EXTENSIONS}=await import('@gltf-transform/extensions'),{MeshoptDecoder}=await import('meshoptimizer');await MeshoptDecoder.ready;const doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read('creator/models/double-strike-demo.glb');const nodes=doc.getRoot().listNodes();const {product}=await import('../creator/products/doubleStrike.js');for(const name of product.configurableMeshes){const n=nodes.find(n=>n.getName()===name);assert(n,'Missing '+name);assert(n.getMesh().listPrimitives()[0].getAttribute('TEXCOORD_0'),'UV '+name)}for(const name of ['BODY_PAINT','BLACK_PLASTIC','METAL','DIAMOND_PLATE_METAL','RUBBER','BOXING_BAG','BALL','LED','GRAPHICS'])assert(doc.getRoot().listMaterials().some(m=>m.getName()===name),'material '+name);assert(fs.statSync('creator/models/double-strike-demo.glb').size<1024*1024);
 const {parseHTML}=require('linkedom');for(const lang of ['en','pl','es','de','fr']){const f=lang==='en'?'creator/index.html':lang+'/creator/index.html';const {document}=parseHTML(fs.readFileSync(f,'utf8'));assert.equal(document.documentElement.lang,lang);assert(document.querySelector('.site-header'));assert(document.querySelector('.footer'));assert(document.querySelector('#creator-root'));assert.equal([...document.querySelectorAll('.desktop-nav a')].filter(a=>a.textContent==='PRO GAMES CREATOR').length,1)}
 for(const file of ['index.html','pl/index.html','es.html','de/index.html','fr/index.html']){const {document}=parseHTML(fs.readFileSync(file,'utf8'));assert(![...document.querySelectorAll('script[src]')].some(s=>s.src.includes('/creator/')),'Homepage loads creator JS')}
 const routes=JSON.parse(fs.readFileSync('vercel.json')).rewrites;assert(routes.some(r=>r.source==='/creator'));assert(routes.some(r=>r.source==='/pl/creator/config/:id'));
 process.env.RESEND_API_KEY='test';process.env.CONTACT_FROM='test@example.com';const handler=require('../api/contact.js');let sent;
 global.fetch=async(url,opts)=>{assert.equal(url,'https://api.resend.com/emails');sent=JSON.parse(opts.body);return {ok:true,json:async()=>({id:'test'})}};
 async function call(body,origin='https://www.progamespoland.com'){const res={statusCode:0,setHeader(){},status(c){this.statusCode=c;return this},json(v){this.body=v;return this}};await handler({method:'POST',headers:{origin,'content-type':'application/json','x-forwarded-for':crypto.randomUUID()},body},res);return res}
 const body={name:'Test',email:'test@example.com',country:'PL',dialCode:'+48',requestId:crypto.randomUUID(),creatorConfiguration:portable(c)};let res=await call(body);assert.equal(res.statusCode,200);assert(sent.text.includes('creatorConfiguration'));assert(sent.text.includes('logo.png'));assert(!sent.text.includes('base64'));res=await call({...body,creatorConfiguration:{...portable(c),bodyColor:'invalid'}});assert.equal(res.statusCode,400);res=await call(body,'https://invalid.example');assert.equal(res.statusCode,403);res=await call({...body,creatorConfiguration:undefined});assert.equal(res.statusCode,200,'Existing contact remains compatible');
 console.log('PASS: configuration validation, persistence, export metadata, GLB mesh/material/UV contract, 5 language shells, isolated homepage loading, Vercel routes, contact API validation and mocked Resend.');
})().catch(e=>{console.error(e);process.exit(1)});
