const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch();const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{const u=new URL(route.request().url());return u.hostname==='127.0.0.1'?route.continue():route.abort()});
const pages=JSON.parse(fs.readFileSync('build/pages.json'));fs.mkdirSync('verification/screenshots',{recursive:true});
for(const p of pages){await page.setViewportSize(p.lang==='pl'?{width:390,height:844}:{width:1440,height:1000});await page.goto('http://127.0.0.1:8000'+p.url);assert.equal(await page.locator('h1').count(),1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),p.url+' horizontal overflow');
if(p.kind==='product'){const buttons=await page.locator('.gallery-swatch[data-index]').count();for(let i=0;i<buttons;i++){await page.locator('.gallery-swatch[data-index]').nth(i).click();await page.waitForFunction(()=>document.querySelector('#productMainImage').getAttribute('aria-busy')==='false');assert(await page.locator('#productMainImage').evaluate(img=>img.complete&&img.naturalWidth>0));assert.equal(await page.locator('.gallery-swatch[aria-pressed="true"]').count(),1)}}
if(p.kind==='home'){assert.equal(await page.locator('.product-card').count(),29);assert.equal(await page.locator('#productInterest option').count(),46);assert.equal(await page.locator('.trade-map-pin').count(),2);await page.locator('.trade-map-pin[data-event="london"]').click();assert((await page.locator('#tradeMapDetail').textContent()).includes('S2201'));await page.locator('#tradeMap').screenshot({path:`verification/screenshots/map-${p.lang}.png`});}
if(p.kind==='collection')assert.equal(await page.locator('.product-card').count(),15);
}
assert.deepEqual(errors,[]);await browser.close();console.log('Browser test passed: 90 pages, variant images, map, layout overflow, no runtime errors.');})().catch(e=>{console.error(e);process.exit(1)});
